### PR TITLE
fix: improve attached code handling for end users

### LINKED ISSUE #1440: mobile_scanner-7.0.0. run exception
version: mobile_scanner-7.0.0
when I run example project, get these errors.

E/flutter (12903): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MobileScannerException(controllerNotAttached, The MobileScannerController has not been attached to MobileScanner. Call start() after the MobileScanner widget is built.)
E/flutter (12903): #0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:340:7)
E/flutter (12903): #1      _MobileScannerAdvancedState.initState (package:mobile_scanner_example/screens/mobile_scanner_advanced.dart:73:27)
E/flutter (12903): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5860:55)
E/flutter (12903): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #163    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #179    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #182    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #188    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #190    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #193    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #202    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7027:14)
E/flutter (12903): #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #206    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #212    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #216    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #218    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #227    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5715:5)
E/flutter (12903): #229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5883:11)
E/flutter (12903): #230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5709:5)
E/flutter (12903): #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4555:16)
E/flutter (12903): #232    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7178:36)
E/flutter (12903): #233    Element.updateChild (package:flutter/src/widgets/framework.dart:4020:18)
E/flutter (12903): #234    Element.updateChildren (package:flutter/src/widgets/framework.dart:4217:11)
E/flutter (12903): #235    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7211:17)
E/flutter (12903): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #239    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #240    StatefulElement.update (package:flutter/src/widgets/framework.dart:5917:5)
E/flutter (12903): #241    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #243    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #244    ProxyElement.update (package:flutter/src/widgets/framework.dart:6059:5)
E/flutter (12903): #245    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #247    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #248    ProxyElement.update (package:flutter/src/widgets/framework.dart:6059:5)
E/flutter (12903): #249    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
E/flutter (12903): #250    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #252    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #253    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #254    StatefulElement.update (package:flutter/src/widgets/framework.dart:5917:5)
E/flutter (12903): #255    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #257    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #258    ProxyElement.update (package:flutter/src/widgets/framework.dart:6059:5)
E/flutter (12903): #259    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
E/flutter (12903): #260    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #262    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #263    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #264    StatefulElement.update (package:flutter/src/widgets/framework.dart:5917:5)
E/flutter (12903): #265    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #268    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #269    StatefulElement.update (package:flutter/src/widgets/framework.dart:5917:5)
E/flutter (12903): #270    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #271    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7034:14)
E/flutter (12903): #272    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #273    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7034:14)
E/flutter (12903): #274    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #276    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #277    ProxyElement.update (package:flutter/src/widgets/framework.dart:6059:5)
E/flutter (12903): #278    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #279    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #280    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #281    ProxyElement.update (package:flutter/src/widgets/framework.dart:6059:5)
E/flutter (12903): #282    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:15)
E/flutter (12903): #283    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5756:16)
E/flutter (12903): #284    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5892:11)
E/flutter (12903): #285    Element.rebuild (package:flutter/src/widgets/framework.dart:5445:7)
E/flutter (12903): #286    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2704:15)
E/flutter (12903): #287    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2762:11)
E/flutter (12903): #288    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3066:18)
E/flutter (12903): #289    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1229:21)
E/flutter (12903): #290    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:482:5)
E/flutter (12903): #291    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
E/flutter (12903): #292    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1355:9)
E/flutter (12903): #293    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1208:5)
E/flutter (12903): #294    _invoke (dart:ui/hooks.dart:316:13)
E/flutter (12903): #295    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:428:5)
E/flutter (12903): #296    _drawFrame (dart:ui/hooks.dart:288:31)
E/flutter (12903): 
D/DecorView[](12903): getWindowModeFromSystem  windowmode is 1
D/DecorView[](12903): updateDecorCaptionStatus displayWindowDecor is false

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1440 
Closes https://github.com/juliansteenbakker/mobile_scanner/pull/1432

### CODE REVIEW

File: lib/src/enums/mobile_scanner_error_code.dart [hunk 1]
```diff
@@ -45,14 +45,122 @@ enum MobileScannerErrorCode {
...
-  ///   when it is initialized.
-  /// - Wait until the widget is fully built before calling start.
+  /// but there is no active [MobileScanner] widget
+  /// for the [MobileScannerController] in the widget tree.
+  ///
+  /// To avoid this error, ensure that a [MobileScanner] widget
+  /// is attached to the widget tree
+  /// when [MobileScannerController.start] is called.
+  ///
+  /// BAD:
```
Comment (navaronbracke) [inline lib/src/enums/mobile_scanner_error_code.dart:55]: I included some examples to clarify this to end users.

@juliansteenbakker If you have more examples, feel free to add these.

File: lib/src/mobile_scanner.dart [hunk 2]
```diff
@@ -328,7 +328,7 @@ class _MobileScannerState extends State<MobileScanner>
   }
 
   @override
-  Future<void> dispose() async {
+  void dispose() {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:331]: This was not needed, since there is no await (we use unawaited instead)

File: lib/src/mobile_scanner_controller.dart [hunk 3]
```diff
@@ -336,13 +339,24 @@ class MobileScannerController extends ValueNotifier<MobileScannerState> {
...
-      throw MobileScannerException(
-        errorCode: MobileScannerErrorCode.controllerNotAttached,
-        errorDetails: MobileScannerErrorDetails(
-          message: MobileScannerErrorCode.controllerNotAttached.message,
-        ),
-      );
+    // If start was called before the MobileScanner widget
+    // had a chance to call its initState method,
+    // wait for it to be called, using a timeout.
+    if (!_isAttachedCompleter.isCompleted) {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner_controller.dart:346]: Instead of letting our users wrap `start()` in a Future (to wait for initState of either the MobileScanner widget, or any parent widget that owns the external controller to complete), we can let the `MobileScanner` widget signal that it is done with `initState()` (using the existing attach method).

Then we just await that future, before proceeding with it.

File: lib/src/mobile_scanner_controller.dart [hunk 4]
```diff
@@ -336,13 +339,35 @@ class MobileScannerController extends ValueNotifier<MobileScannerState> {
...
+      // The timeout is currently an arbitrary value,
+      // which should be long enough for the next frame
+      // to propagate any pending changes to the widget tree.
+      await _isAttachedCompleter.future
+          .timeout(const Duration(milliseconds: 500))
```
Comment (navaronbracke) [inline lib/src/mobile_scanner_controller.dart:351]: Suggestions for improving the timeout are welcome. The timeout only applies if the completer has not yet completed, so this should be an edge case.

File: lib/src/mobile_scanner_controller.dart [hunk 5]
```diff
@@ -531,16 +556,21 @@ class MobileScannerController extends ValueNotifier<MobileScannerState> {
...
     await MobileScannerPlatform.instance.dispose();
   }
 
-  /// Keeps track if the controller is correctly attached to the MobileScanner
-  /// widget.
+  /// Signal to this [MobileScannerController] that it is attached
+  /// to a [MobileScanner] widget.
+  ///
+  /// This method is called by `_MobileScannerState.initState()`.
   void attach() {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner_controller.dart:572]: @juliansteenbakker Any clue on how to make this method private to the package ? maybe with a mixin that is not exported in the `mobile_scanner.dart` file?

File: pubspec.yaml [hunk 6]
```diff
@@ -21,6 +21,7 @@ dependencies:
     sdk: flutter
   flutter_web_plugins:
     sdk: flutter
+  meta: ">=1.16.0"
```
Comment (navaronbracke) [inline pubspec.yaml:24]: We already have an implicit dependency on meta 1.16.0 in the pubspec.lock, so I just made it explicit, without an upper bound. (since we currently only need the `@internal` annotation)

File: lib/src/mobile_scanner_controller.dart (hunk 5 above)
Comment (navaronbracke) [reply lib/src/mobile_scanner_controller.dart:572]: I went with the `@internal` annotation from `package:meta`, which is exactly for this purpose.

File: lib/src/enums/mobile_scanner_error_code.dart (hunk 1 above)
Comment (juliansteenbakker) [reply lib/src/enums/mobile_scanner_error_code.dart:55]: Should we also empathise the use of `autoStart`, which is the default option?

Comment (navaronbracke) [reply lib/src/enums/mobile_scanner_error_code.dart:55]: I can add a sample for that. Although if you use autoStart, you will not hit the bug (since the widget then does it correctly internally). I'll just put that explanation in that sample

File: lib/src/mobile_scanner_controller.dart (hunk 5 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner_controller.dart:572]: Looks good to me!

File: lib/src/mobile_scanner_controller.dart (hunk 4 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner_controller.dart:351]: What about `await WidgetsBinding.instance.endOfFrame`?

**Comment by juliansteenbakker** [comment]
Hi @navaronbracke, all looks good to me, except maybe we can improve the following:

```dart
    // If start was called before the MobileScanner widget
    // had a chance to call its initState method,
    // wait for it to be called, using a timeout.
    if (!_isAttachedCompleter.isCompleted) {
      // The timeout is currently an arbitrary value,
      // which should be long enough for the next frame
      // to propagate any pending changes to the widget tree.
      await _isAttachedCompleter.future
          .timeout(const Duration(milliseconds: 500))
          .catchError((Object error, StackTrace stackTrace) {
            throw MobileScannerException(
              errorCode: MobileScannerErrorCode.controllerNotAttached,
              errorDetails: MobileScannerErrorDetails(
                message: MobileScannerErrorCode.controllerNotAttached.message,
                details: stackTrace.toString(),
              ),
            );
          });

      // Abort if the controller was disposed
      // while waiting for the widget to be attached.
      if (_isDisposed) {
        throw MobileScannerException(
          errorCode: MobileScannerErrorCode.controllerDisposed,
          errorDetails: MobileScannerErrorDetails(
            message: MobileScannerErrorCode.controllerDisposed.message,
          ),
        );
      }
    }
```

To:


```dart
    // If start was called before the MobileScanner widget
    // had a chance to call its initState method,
    // wait for it to be called, using a timeout.
    if (!_isAttachedCompleter.isCompleted) {
      // Wait for the next frame, which ensures the widget tree has settled
      await WidgetsBinding.instance.endOfFrame;

      // If the Completer still isn't completed after the frame, throw an error
      if (!_isAttachedCompleter.isCompleted) {
        throw MobileScannerException(
          errorCode: MobileScannerErrorCode.controllerNotAttached,
          errorDetails: MobileScannerErrorDetails(
            message: MobileScannerErrorCode.controllerNotAttached.message,
          ),
        );
      }

      if (_isDisposed) {
        throw MobileScannerException(
          errorCode: MobileScannerErrorCode.controllerDisposed,
          errorDetails: MobileScannerErrorDetails(
            message: MobileScannerErrorCode.controllerDisposed.message,
          ),
        );
      }
    }
```

File: lib/src/mobile_scanner_controller.dart (hunk 4 above)
Comment (navaronbracke) [reply lib/src/mobile_scanner_controller.dart:351]: @juliansteenbakker I see that this got merged without that adjustment. Is there a reason not to use `await WidgetsBinding.instance.endOfFrame` ?

Comment (juliansteenbakker) [reply lib/src/mobile_scanner_controller.dart:351]: Because it still does not guarantee that initState() is done as far as i can tell.
