### PR TITLE
fix(orientation): refactor orientation detection and fix related issues

### LINKED ISSUE #1462: android tablet landscape issue
when i use below code on android tablet landscape the camera is showing portrait mode,unable to scan qr code on landscape 

   OrientationBuilder(
            builder: (context, orientation) {
              return LayoutBuilder(
                builder: (context, constraints) {
                  return MobileScanner(
                    key: ValueKey(orientation),
                    controller: controller,
                    onDetect: (capture) {
                      final List<Barcode> barcodes = capture.barcodes;
                      if (barcodes.isNotEmpty) {
                        final String? scannedCode = barcodes.first.rawValue;
                        if (scannedCode != null && scannedCode.isNotEmpty) {
                          controller.stop();
                          widget.onScan(scannedCode);
                        }
                      }
                    },
                    fit: widget.fit,
                    scanWindow: widget.scanWindow,
                  );
                },
              );
            },
          )

### LINKED ISSUE #1474: BarcodeOverlay misalignment after orientation change
When using the mobile_scanner_example, the BarcodeOverlay does not correctly align with the barcode position on the MobileScanner after an orientation change. Specifically, this occurs when rotating the device from portrait to landscape, or from landscape back to portrait. The overlay appears to be offset or mispositioned relative to the detected barcode.

### LINKED ISSUE #1486: Android: App screen rotates to portrait when MobileScanner is initialized, even with landscape lock
When using `mobile_scanner: ^7.0.0` in a Flutter app for Android Tablet Emulator, the app is locked to landscape orientation using both Dart and AndroidManifest.xml. However, when the MobileScanner widget is shown, the emulator screen automatically rotates to portrait and display a toast ("Rotate for a best view"), while the camera preview remains in landscape.

### Steps to Reproduce:
1. Lock orientation to landscape in `main.dart`:
```
await SystemChrome.setPreferredOrientations([
  DeviceOrientation.landscapeLeft,
  DeviceOrientation.landscapeRight,
]);
```

2. Lock orientation in `AndroidManifest.xml`:
```
<activity
    android:name=".MainActivity"
    android:screenOrientation="landscape"
    ... />
```

3. Add a `MobileScanner` widget to the UI as shown below.

4. Run the app on an Android Tablet Emulator.

5. Observe that the app screen rotates to portrait when the camera preview is shown, but the preview itself stays landscape.

### Relevant Code:

```
// CAMERA PREVIEW FOR BARCODE SCANNER
Positioned(
  bottom: 12.0,
  left: 12.0,
  child: Builder(
    builder: (context) {
      final double previewWidth =
          MediaQuery.of(context).size.width * 0.2;
      final double previewHeight = previewWidth / 4 * 3;
      return SizedBox(
        width: previewWidth,
        height: previewHeight,
        child: MobileScanner(
          onDetect: (barcodeCapture) {
            if (_showDialogOverlay) return;
            final List<Barcode> barcodes =
                barcodeCapture.barcodes;
            if (barcodes.isNotEmpty) {
              final barcode = barcodes.first;
              final code = barcode.rawValue ?? '';
              if (code.isNotEmpty) {
                _searchItemAsync(code);
              }
            }
          },
        ),
      );
    },
  ),
),
```

### Expected Behavior:
The app screen and camera preview should remain in landscape orientation at all times.

### Screen Record:
https://github.com/user-attachments/assets/1be8043d-0a82-4a61-88ba-c9d7970d18b7

### Additional Context:
- Flutter version: 3.29.3
- `mobile_scanner` version: ^7.0.0
- Android Emulator: Pixel Tablet, API 36 "Baklava", Android 16.0
- Orientation lock confirmed in both Dart and Manifest

### Workarounds Tried:
- Locking orientation in MainActivity
- Disabling auto-rotate in emulator
- Forcing orientation in build method

None of these resolved the issue.

### PR DESCRIPTION
**Pull request by abbashosseinii**
This PR fixes several orientation-related issues by refactoring the orientation detection
  on Android.

  Changes:

   * Android: Replaced the BroadcastReceiver for ACTION_CONFIGURATION_CHANGED with an
     OrientationEventListener to get the physical device orientation instead of the UI
     orientation.
   * Overlay: The BarcodePainter now receives the deviceOrientation and adjusts the
     cameraPreviewSize accordingly, fixing the barcode overlay alignment on orientation
     change.
   * Version: Bumped version to 7.1.3.

  Related Issues:

  Fixes #1486
  Fixes #1474
  Fixes #1462

### CODE REVIEW

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 1]
```diff
@@ -290,42 +290,7 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
-        case .landscapeLeft:
-            videoOrientation = .landscapeLeft
-        case .landscapeRight:
-            videoOrientation = .landscapeRight
-        default:
-            videoOrientation = .portrait
-        }
-
-        return videoOrientation
+        return UIDevice.current.orientation.videoOrientation
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift]: UIDeviceOrientation doesn't have a `videoOrientation` member?

https://developer.apple.com/documentation/uikit/uidevice/orientation

Or am I looking in the wrong place?

Isn't this the old switch case above? And what with the old comment:

```
// Get the orientation from the window scene if available
// When the app's orientation is fixed and the app orientation is actually different from the device orientation, it malfunctions.
```

does that still apply?

**Review by navaronbracke — COMMENTED** [review]
Overall this is LGTM, except for one question on iOS.

Also, this needs a changelog entry.

**Comment by FelipeABastos** [comment]
Nice one! Any estimate on when this will be merged?

**Comment by juliansteenbakker** [comment]
@FelipeABastos I have a very busy week this week, so i'm aiming for next week.

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift (hunk 1 above)
Comment (abbashosseinii) [reply darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift]: Thanks for the thorough review and the LGTM—much appreciated!
Regarding your question on the iOS orientation handling: I've reverted those changes in [this commit](https://github.com/juliansteenbakker/mobile_scanner/pull/1552/commits/c13bb7178d0038c95ba5b8ba60bc74b879552215) because I don't have access to physical iOS devices to fully test the UIDeviceOrientation logic and ensure it aligns with the window scene fallback (or avoids the issues noted in the old comment). I was only able to verify the fixes on Android, so I'd prefer to hold off on iOS until I can test properly or get some guidance/eyes on it from the team.
If you'd like to take a stab at refining that part (or point me to the right approach for the videoOrientation mapping), I'm all ears—happy to iterate! Otherwise, let me know if this works for merging the Android-focused fixes as-is.
(Added a changelog entry for the Android refactors)

**Review by navaronbracke — APPROVED** [review]
LGTM!

**Review by navaronbracke — CHANGES_REQUESTED** [review]
One more thing, it seems that one of the files was not formatted, using the 80 character line length limit:

```
   info • The line length exceeds the 80-character limit • lib/src/overlay/barcode_painter.dart:61:81 • lines_longer_than_80_chars
   info • The line length exceeds the 80-character limit • lib/src/overlay/barcode_painter.dart:73:81 • lines_longer_than_80_chars
```

**Comment by abbashosseinii** [comment]
Also fixed a couple of long-line lints in the painter for good measure.

**Review by navaronbracke — APPROVED** [review]

**Comment by breezechime** [comment]
Is it surprising that the rotation direction of the phone is completely based on it, without even providing a parameter to lock the rotation?
