### PR TITLE
fix: migrate rawBytes to byte array from payloadStringValue.

### LINKED ISSUE #1444: Different rawBytes output when upgrading from v5 to v7
I am encoding arrays of bytes into aztec code using the go package `github.com/boombuler/barcode/aztec`. Since upgrading the `mobile_scanner` from version 5 to 7 I am seeing different outputs for the `rawBytes` value when scanning the aztec code using this package.

Image

I created this test code which encodes the bytes for `hellø` (note the final `ø`) (which are `[104, 101, 108, 108, 195, 184]`). The previous version of this package successfully returned the exact same byte array on iOS and Android. Scanning this code on the new version however returns different values on both web and iOS.

- iOS: `[226, 76, 214, 250, 44, 59, 140, 0]`
- Web: `[226, 76, 214, 252, 88, 119, 24]`

I am not sure where to go from here. It appears that the way the result is encoded has changed since the upgrade and is inconsistent in both the web and mobile versions. Does anyone have any ideas why this would be the case?

The code which captured the byte arrays was:

```dart

  void _onDetect(BarcodeCapture capture, DetectStopFunc stop) async {
    for (final barcode in capture.barcodes) {
      if (barcode.rawBytes != null) {
        debugPrint("Raw bytes: ${barcode.rawBytes}");
      }
    }
  }
```

I tried the same tests when encoding the bytes for the string `hello` (standard `o`) and both the web and iOS returned the same byte array. This could suggest that there is some encoding difference somewhere?

Any help would be greatly appreciated :)

### PR DESCRIPTION
**Pull request by juliansteenbakker**
This PR possibly fixed #1444, #1357 and #1317 by getting the bytes from the string value instead of `payloadData`.

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
I have updated the barcode parser on apple, and it now correctly decodes the codes mentioned in #1444, #1357 and #1317.

I have added docs to the readme explaining the difference between the frameworks and limitations on apple. However, i think this PR will fix most issues regarding rawBytes on apple.

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 1]
```diff
@@ -1129,8 +1157,9 @@ extension VNBarcodeObservation {
             ],
             "format": symbology.toInt ?? -1,
             "rawBytes": rawBytes,
+            "rawPayloadData": rawPayloadData,
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:1172]: I find this a bit unfortunate. The "raw bytes" is the entire payload data, but we also provide the "raw bytes without header & padding bytes".

Maybe we can use `"rawBytes"` and `"decodedPayloadBytes"` ? Naming is hard. Thoughts?

File: example/lib/widgets/scanned_barcode_label.dart [hunk 2]
```diff
@@ -28,8 +24,36 @@ class ScannedBarcodeLabel extends StatelessWidget {
           );
         }
 
+        final String displayValues = scannedBarcodes
```
Comment (navaronbracke) [inline example/lib/widgets/scanned_barcode_label.dart]: Only do this in the if check below?

File: example/lib/widgets/scanned_barcode_label.dart [hunk 3]
```diff
@@ -28,8 +24,36 @@ class ScannedBarcodeLabel extends StatelessWidget {
...
+
+        if (scannedBarcodes.any((e) => e.displayValue != null)) {
+          return Text(
+            'Display values: $displayValues',
+            overflow: TextOverflow.fade,
+            style: const TextStyle(color: Colors.white),
+          );
+        }
+
+        final String rawValues = scannedBarcodes
```
Comment (navaronbracke) [inline example/lib/widgets/scanned_barcode_label.dart]: Same here

File: darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+/// codes), the caller falls back to the ISO-Latin-1 round-trip on
+/// `payloadStringValue`, which correctly recovers ASCII bytes for those modes.
+///
+/// **Limitations, see README for full details:**
+/// - Kanji mode (0x08) is not yet supported and will cause this parser to
+///   return `nil`, falling through to the Latin-1 fallback which cannot
+///   round-trip Japanese characters.
+/// - Aztec, DataMatrix, and PDF417 are handled separately via the ISO-Latin-1
+///   round-trip in the plugin, which has its own constraints.
+enum BarcodePayloadParser {
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift:22]: Do we need a unit test for this class?

File: lib/src/objects/barcode.dart [hunk 5]
```diff
@@ -128,6 +130,8 @@ class Barcode {
   /// This value may be multiline if line breaks are encoded in the barcode.
   /// This value may include the supplement value.
   ///
+  /// On Apple (iOS & macOS) this value will always be UTF-8.
```
Comment (navaronbracke) [inline lib/src/objects/barcode.dart]: Per https://api.dart.dev/dart-core/String-class.html strings in Dart are always UTF-16. I would omit this line, since the user can access the code points of the Dart string as-is?

File: lib/src/objects/barcode.dart [hunk 6]
```diff
@@ -151,7 +155,15 @@ class Barcode {
   /// This is null if the raw bytes are not available.
   final Uint8List? rawBytes;
 
-  /// The raw value of `UTF-8` encoded barcodes.
+  /// The raw bytes of the barcode, including header & padding bytes.
+  /// Only available on Apple (iOS & macOS).
+  ///
+  /// If the barcode data is not UTF-8 encoded, this is the only way to access
+  /// the data.
+  final Uint8List? rawPayloadData;
```
Comment (navaronbracke) [inline lib/src/objects/barcode.dart]: I understand that you wish to add a new field to work around this. However, my personal opinion is that this pollutes the API a little bit.

What if we do the following?

1. Deprecate `final Uint8List? rawBytes;`
2. Add a new field `final BarcodeBytes? rawDecodedBytes;`
3. Create a sealed class `BarcodeBytes`, with two subclasses, of which the special one is used by iOS/macOS.

```
sealed class BarcodeBytes {
  const BarcodeBytes();
}

final class DecodedBarcodeBytes extends BarcodeBytes {
  const DecodedBarcodeBytes(this.bytes);

  /// The decoded raw bytes of the barcode value, without header or padding bytes.
  final Uint8List bytes;
}

final class DecodedVisionBarcodeBytes extends BarcodeBytes {
  const DecodedVisionBarcodeBytes({required this.bytes, required this.rawBytes});

  /// The decoded raw bytes of the barcode value, without header or padding bytes.
  final Uint8List? decodedBytes;

  /// The raw bytes of the barcode from the Vision API.
  /// If the bytes of the original barcode are not encoded in UTF-8, this field can be used to do a manual conversion.
  final Uint8List? rawBytes;
}
```

We can then also move the docs for the limitation in this class, rather than in the README.

**Review by navaronbracke — CHANGES_REQUESTED** [review]

File: lib/src/objects/barcode.dart (hunk 6 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode.dart]: Yeah, this is better, as it doesn't produce empty parameters for certain platforms

File: darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift (hunk 4 above)
Comment (juliansteenbakker) [reply darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift:22]: We currently don't have any apple native tests, maybe we can add that in a separate PR?

Comment (navaronbracke) [reply darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift:22]: We can do that, yes. I have some experience with writing those.

**Comment by juliansteenbakker** [comment]
I've updated the docs and added `rawDecodedBytes`. @navaronbracke what do you think?

File: example/lib/widgets/scanned_barcode_label.dart [hunk 7]
```diff
@@ -28,8 +24,36 @@ class ScannedBarcodeLabel extends StatelessWidget {
           );
         }
 
+        if (scannedBarcodes.any((e) => e.displayValue != null)) {
+          final String displayValues = scannedBarcodes
```
Comment (navaronbracke) [inline example/lib/widgets/scanned_barcode_label.dart:28]: Should we filter on the non-null display values?

File: lib/src/objects/barcode.dart [hunk 8]
```diff
@@ -55,6 +57,21 @@ class Barcode {
     final barcodeWidth = size?['width'] as double?;
     final barcodeHeight = size?['height'] as double?;
 
+    final rawBytesData = data['rawBytes'] as Uint8List?;
+    final rawPayloadData = data['rawPayloadData'] as Uint8List?;
+
+    final BarcodeBytes? rawDecodedBytes;
+    if (rawPayloadData != null) {
```
Comment (navaronbracke) [inline lib/src/objects/barcode.dart:64]:
```suggestion
            if (rawPayloadData != null) {
        final BarcodeBytes? rawDecodedBytes = switch(data) {
          case {'rawPayloadData': final Uint8List rawPayloadData, 'rawBytes': final Uint8List? rawBytesData } => DecodedVisionBarcodeBytes(
                decodedBytes: rawBytesData,
                rawBytes: rawPayloadData,
              ),
           case {'rawBytes': final Uint8List rawBytesData } => DecodedBarcodeBytes(bytes: rawBytesData),
           _ => null,
        };
```

File: lib/src/objects/barcode.dart [hunk 9]
```diff
@@ -149,14 +169,25 @@ class Barcode {
...
+  ///
+  /// This is either a [DecodedBarcodeBytes] (on Android and web)
+  /// or a [DecodedVisionBarcodeBytes] (on Apple platforms),
+  /// which may contain both decoded bytes and raw payload bytes.
+  ///
+  /// This is null if the raw bytes are not available.
+  final BarcodeBytes? rawDecodedBytes;
+
+  /// The raw value of `UTF-8` encoded barcodes on Android.
+  /// On Apple (iOS and macOS), this value can also be Latin-1 (ISO 8859-1)
```
Comment (navaronbracke) [inline lib/src/objects/barcode.dart]: The line "On Apple (iOS and macOS), this value can also be Latin-1 (ISO 8859-1)" is incorrect? We take a Latin-1 string and convert it back to UTF-8 for Dart?

File: lib/src/objects/barcode_bytes.dart [hunk 10]
```diff
@@ -0,0 +1,35 @@
+import 'dart:typed_data';
+
+/// Represents the raw bytes of a barcode.
+sealed class BarcodeBytes {
+  const BarcodeBytes();
+}
+
+/// Decoded barcode bytes, available on all platforms.
```
Comment (navaronbracke) [inline lib/src/objects/barcode_bytes.dart]: This phrase is not true? Since this is used on Android and web, but not MacOS/iOS

File: lib/src/objects/barcode_bytes.dart [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+final class DecodedBarcodeBytes extends BarcodeBytes {
+  /// Creates a new [DecodedBarcodeBytes] instance.
+  const DecodedBarcodeBytes({required this.bytes});
+
+  /// The decoded raw bytes of the barcode value.
```
Comment (navaronbracke) [inline lib/src/objects/barcode_bytes.dart]:
```suggestion
  /// The decoded raw bytes of the barcode value.
  ///
  /// This excludes any header or padding bytes.
```

File: test/objects/barcode_test.dart [hunk 12]
```diff
@@ -134,8 +137,29 @@ void main() {
...
+        expect(barcode.rawDecodedBytes, isA<DecodedBarcodeBytes>());
+        final decoded = barcode.rawDecodedBytes! as DecodedBarcodeBytes;
+        expect(decoded.bytes, rawBytes);
       });
 
+      test(
+        'creates DecodedVisionBarcodeBytes with rawBytes and rawPayloadData',
+        () {
+          final rawBytes = Uint8List.fromList([72, 101, 108, 108, 111]);
+          final rawPayloadData = Uint8List.fromList([0, 1, 72, 101, 108]);
```
Comment (navaronbracke) [inline test/objects/barcode_test.dart]: Just for correctness of the test, should this be a superset of `rawBytes` ?

File: test/objects/barcode_test.dart [hunk 13]
```diff
@@ -134,8 +137,29 @@ void main() {
...
+          final barcode = Barcode.fromNative(<Object?, Object?>{
+            'rawBytes': rawBytes,
+            'rawPayloadData': rawPayloadData,
+          });
+
+          expect(barcode.rawBytes, rawBytes);
+          expect(barcode.rawDecodedBytes, isA<DecodedVisionBarcodeBytes>());
+          final decoded = barcode.rawDecodedBytes! as DecodedVisionBarcodeBytes;
```
Comment (navaronbracke) [inline test/objects/barcode_test.dart:160]: I know we are not testing the byte ranges here, should we do that and in the other test?

**Review by navaronbracke — CHANGES_REQUESTED** [review]

File: example/lib/widgets/scanned_barcode_label.dart (hunk 7 above)
Comment (juliansteenbakker) [reply example/lib/widgets/scanned_barcode_label.dart:28]: Yes, i'll add `.whereType<String>()`

File: lib/src/objects/barcode.dart (hunk 8 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode.dart:64]: Do you think this notation is better/cleaner? imho, it's not as easy to read as the if else statement.

Comment (navaronbracke) [reply lib/src/objects/barcode.dart:64]: I'm fine with either

File: lib/src/objects/barcode.dart (hunk 9 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode.dart]: The conversion happens for displayValue/rawBytes, not for rawValue.

File: darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift (hunk 4 above)
Comment (juliansteenbakker) [reply darwin/mobile_scanner/Sources/mobile_scanner/BarcodePayloadParser.swift:22]: I've created https://github.com/juliansteenbakker/mobile_scanner/issues/1658 for tracking

File: lib/src/objects/barcode_bytes.dart (hunk 10 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode_bytes.dart]: Yeah, i was thinking wrong, like raw bytes is available for all platforms, but i've updated the docs.

File: lib/src/objects/barcode.dart (hunk 9 above)
Comment (navaronbracke) [reply lib/src/objects/barcode.dart]: True, but Dart strings are still UTF-16

File: example/lib/widgets/scanned_barcode_label.dart (hunk 7 above)
Comment (navaronbracke) [reply example/lib/widgets/scanned_barcode_label.dart:28]: `nonNulls` is a bit more concise though?

File: lib/src/objects/barcode_bytes.dart (hunk 11 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode_bytes.dart]: Maybe we should change this to match `DecodedVisionBarcodeBytes` `decodedBytes`? As it is the same value, so i would expect the same docs and same parameter name. Or we should change `decodedBytes` to `bytes`...

File: lib/src/objects/barcode.dart (hunk 9 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode.dart]: I'll update the doc, outlining that while the value is latin-1 on the native side, the platform channel will convert this.

File: lib/src/objects/barcode_bytes.dart (hunk 11 above)
Comment (navaronbracke) [reply lib/src/objects/barcode_bytes.dart]: Maybe do both?

File: example/lib/widgets/scanned_barcode_label.dart (hunk 7 above)
Comment (juliansteenbakker) [reply example/lib/widgets/scanned_barcode_label.dart:28]: Ah yeah that's better

File: lib/src/objects/barcode_bytes.dart (hunk 11 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode_bytes.dart]: Good idea!

File: test/objects/barcode_test.dart (hunk 12 above)
Comment (juliansteenbakker) [reply test/objects/barcode_test.dart]: Yeah that's more realistic

File: test/objects/barcode_test.dart (hunk 13 above)
Comment (juliansteenbakker) [reply test/objects/barcode_test.dart:160]: I've added the actual byte comparison for completeness.

File: lib/src/objects/barcode_bytes.dart [hunk 14]
```diff
@@ -0,0 +1,36 @@
...
+/// On Apple platforms, the Vision API may provide both decoded bytes
+/// (without header/padding) and the raw payload bytes
+/// (including header and padding).
+final class DecodedVisionBarcodeBytes extends BarcodeBytes {
+  /// Creates a new [DecodedVisionBarcodeBytes] instance.
+  const DecodedVisionBarcodeBytes({this.bytes, this.rawBytes});
+
+  /// The decoded raw bytes of the barcode value,
+  /// without header or padding bytes.
+  final Uint8List? bytes;
```
Comment (navaronbracke) [inline lib/src/objects/barcode_bytes.dart:29]: I still wonder about the nullability here.

1. No valid bytes at all, in which case `rawBytes` and `rawDecodedBytes` is null.
2. DecodedBarcodeBytes for platforms other than iOS/MacOS
3. Valid bytes on iOS/MacOS, so a DecodedVisionBarcodeBytes, where `bytes` is null if decoding of the raw bytes failed.

For 3, can `rawBytes` ever be null actually? Don't we just have `final BarcodeBytes? rawDecodedBytes == null` in that case? (so if we can't get the actual raw bytes, we won't decode them and `BarcodeCapture.BarcodeBytes` is null anyway)

**Review by navaronbracke — CHANGES_REQUESTED** [review]
LGTM, except one thing I'm not sure about.

File: lib/src/objects/barcode_bytes.dart (hunk 14 above)
Comment (juliansteenbakker) [reply lib/src/objects/barcode_bytes.dart:29]: We can safely make `rawBytes` non nullable.

File: lib/src/objects/barcode_bytes.dart [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+///
+/// On Apple platforms, the Vision API may provide both decoded bytes
+/// (without header/padding) and the raw payload bytes
+/// (including header and padding).
+final class DecodedVisionBarcodeBytes extends BarcodeBytes {
+  /// Creates a new [DecodedVisionBarcodeBytes] instance.
+  const DecodedVisionBarcodeBytes({required this.rawBytes, this.bytes});
+
+  /// The decoded raw bytes of the barcode value,
+  /// without header or padding bytes.
```
Comment (navaronbracke) [inline lib/src/objects/barcode_bytes.dart:28]:
```suggestion
  /// without header or padding bytes.
  ///
  /// This is null if removing the header or padding bytes from [rawBytes] failed.
```

Comment (juliansteenbakker) [reply lib/src/objects/barcode_bytes.dart:28]: Fixed directly on develop.
