### PR TITLE
fix: black screen after multiple initialization

### LINKED ISSUE #493: Scanner stops working after reopening screen
The first time the scan screen is opened it works fine, but after i close it and open it again it stops detecting codes.

I'm trying disposing the controller and starting it on initstate

```
@override
void initState() {
  controller.start();
  super.initState();
}

@override
void dispose() {
  controller.dispose();
  super.dispose();
}
```

These are the logs when opening the scan screen for the second time.

> D/TransportRuntime.SQLiteEventStore(11912): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(11912): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/DeferrableSurface(11912): Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@3c19fab}
D/CameraOrientationUtil(11912): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
I/chatty  (11912): uid=10479(com.vavastone.driver) identical 1 line
D/CameraOrientationUtil(11912): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/DeferrableSurface(11912): Surface created[total_surfaces=2, used_surfaces=0](androidx.camera.core.impl.ImmediateSurface@6aa9fc6}
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Use case androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382 ACTIVE
D/UseCaseAttachState(11912): Active and attached use case: [] for camera: 0
D/CameraOrientationUtil(11912): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Use case androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471 ACTIVE
D/CameraOrientationUtil(11912): getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=90, isOppositeFacing=true, result=90
D/UseCaseAttachState(11912): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Use cases [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] now ATTACHED
D/UseCaseAttachState(11912): All use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/UseCaseAttachState(11912): Active and attached use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Resetting Capture Session
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Releasing session in state INITIALIZED
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Attempting to force open the camera.
D/CameraStateRegistry(11912): tryOpenCamera(Camera@b772065[id=0]) [Available Cameras: 1, Already Open: false (Previous state: CLOSED)] --> SUCCESS
D/CameraStateRegistry(11912): Recalculating open cameras:
D/CameraStateRegistry(11912): Camera                                       State                 
D/CameraStateRegistry(11912): -------------------------------------------------------------------
D/CameraStateRegistry(11912): Camera@b772065[id=0]                         OPENING               
D/CameraStateRegistry(11912): Camera@acbf1c7[id=1]                         UNKNOWN               
D/CameraStateRegistry(11912): -------------------------------------------------------------------
D/CameraStateRegistry(11912): Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Opening camera.
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine(11912): New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine(11912): Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState(11912): All use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
E/libc    (11912): Access denied finding property "persist.vendor.camera.privapp.list"
W/CameraX-core_ca(11912): type=1400 audit(0.0:10551729): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=23634 scontext=u:r:untrusted_app:s0:c223,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0
W/Binder:11912_5(11912): type=1400 audit(0.0:10551730): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=23634 scontext=u:r:untrusted_app:s0:c223,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0
W/Binder:11912_5(11912): type=1400 audit(0.0:10551732): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=23634 scontext=u:r:untrusted_app:s0:c223,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0
E/libc    (11912): Access denied finding property "vendor.camera.aux.packagelist"
E/CameraManagerGlobal(11912): Camera 61 is not available. Ignore physical camera status change
E/libc    (11912): Access denied finding property "vendor.camera.aux.packagelist"
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Use case androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382 ACTIVE
D/UseCaseAttachState(11912): Active and attached use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Use case androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471 ACTIVE
D/UseCaseAttachState(11912): Active and attached use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Issue capture request
D/UseCaseAttachState(11912): Active and attached use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} CameraDevice.onOpened()
D/Camera2CameraImpl(11912): {Camera@b772065[id=0]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry(11912): Recalculating open cameras:
D/CameraStateRegistry(11912): Camera                                       State                 
D/CameraStateRegistry(11912): -------------------------------------------------------------------
D/CameraStateRegistry(11912): Camera@b772065[id=0]                         OPEN                  
D/CameraStateRegistry(11912): Camera@acbf1c7[id=1]                         UNKNOWN               
D/CameraStateRegistry(11912): -------------------------------------------------------------------
D/CameraStateRegistry(11912): Open count: 1 (Max allowed: 1)
D/CameraStateMachine(11912): New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine(11912): Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState(11912): All use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/UseCaseAttachState(11912): Active and attached use case: [androidx.camera.core.Preview-af7e5d6f-aa02-4810-bb5a-025f31827062154886382, androidx.camera.core.ImageAnalysis-2840e1fa-af4c-416c-bb47-c00f37a77cdb199555471] for camera: 0
D/SyncCaptureSessionBase(11912): [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@36dee4e] getSurface...done
D/CaptureSession(11912): Opening capture session.
D/DeferrableSurface(11912): New surface in use[total_surfaces=2, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@3c19fab}
D/DeferrableSurface(11912): use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@3c19fab
D/DeferrableSurface(11912): New surface in use[total_surfaces=2, used_surfaces=2](androidx.camera.core.impl.ImmediateSurface@6aa9fc6}
D/DeferrableSurface(11912): use count+1, useCount=1 androidx.camera.core.impl.ImmediateSurface@6aa9fc6
D/CaptureSession(11912): Attempting to send capture request onConfigured
D/CaptureSession(11912): Issuing request for session.
D/Camera2CaptureRequestBuilder(11912): createCaptureRequest
D/CaptureSession(11912): Issuing capture request.
D/Camera2CaptureRequestBuilder(11912): createCaptureRequest
D/CaptureSession(11912): CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession(11912): CameraCaptureSession.onReady() OPENED
D/TransportRuntime.CctTransportBackend(11912): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
I/DpmTcmClient(11912): RegisterTcmMonitor from: $Proxy1
W/System  (11912): A resource failed to call release. 
I/BpBinder(11912): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
I/TransportRuntime.CctTransportBackend(11912): Status Code: 200
I/TransportRuntime.CctTransportBackend(11912): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(11912): Content-Encoding: gzip

### LINKED ISSUE #589: Camera does not work after navigation from one screen to another (Both use MobileScanner)
Every time when i am trying to navigate from one screen to another (both screens use MobileScanner), on the second screen i receive white screen if i do not use autostart and starting/stopping controller by myself. If i use autostart, i receive black screen

**Package:** mobile_scanner: 3.2.0
**iOS Device:** iPad Pro 12.9 inch (5th generation)
**iPadOS:** 16.4
**Android Device:** Samsung Galaxy Tab S7
**Android version:** Android 11

**Code:**

```
class ScannerOne extends StatefulWidget {
  const ScannerOne({super.key});

  @override
  State<ScannerOne> createState() => _ScannerOneState();
}

class _ScannerOneState extends State<ScannerOne> {

  final MobileScannerController controller = MobileScannerController(autoStart: false);

  @override
  void initState() {
    controller.start();
    super.initState();
  }

  @override
  void dispose() {
    controller.stop();
    controller.dispose();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'scanner 1',
        ),
        leading: IconButton(
            onPressed: () => Modal().show(context),
            icon: Container(
              width: 50,
              height: 50,
              color: Colors.red,
            )),
      ),
      body: MobileScanner(
        controller: controller,
        onDetect: (_) {},
      ),
    );
  }
}

class ScannerTwo extends StatefulWidget {
  const ScannerTwo({super.key});

  @override
  State<ScannerTwo> createState() => _ScannerTwoState();
}

class _ScannerTwoState extends State<ScannerTwo> {

  final MobileScannerController controller = MobileScannerController(autoStart: false);

  @override
  void initState() {
    controller.start();
    super.initState();
  }

  @override
  void dispose() {
    controller.stop();
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'scanner 2',
        ),
        leading: IconButton(
          onPressed: () => Modal().show(context),
          icon: Container(
            width: 50,
            height: 50,
            color: Colors.red,
          ),
        ),
      ),
      body: MobileScanner(
        controller: controller,
        onDetect: (_) {},
      ),
    );
  }
}

class Modal {
  show(BuildContext context) {
    return showDialog(
      context: context,
      builder: (context) {
        return Dialog(
          child: Column(
            children: [
              CupertinoButton(
                child: const Text('Scanner 1'),
                onPressed: () {
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const ScannerOne(),
                    ),
                  );
                },
              ),
              CupertinoButton(
                child: const Text('Scanner 2'),
                onPressed: () {
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const ScannerTwo(),
                    ),
                  );
                },
              )
            ],
          ),
        );
      },
    );
  }
}
``` 

**Console: output:**

```
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:674:9)
<asynchronous suspension>

while de-activating platform stream on channel dev.steenbakker.mobile_scanner/scanner/event

flutter: mobile_scanner: not starting automatically because autoStart is set to false in the controller.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: code genericError, message: Called start() while already started!
#0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:210:7)
<asynchronous suspension>
```

**Actual result when autostart false:** 
IMG_0614

**Actual result when autoStart true:**
IMG_0613

**Flutter doctor:**

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/aleksey/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/aleksey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 73.0.3
    • Dart plugin version 223.8888

[✓] Connected device (3 available)
    • iPad (mobile) • 00008103-000248A82E53001E • ios            • iOS 16.4 20E5229e
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

https://user-images.githubusercontent.com/101318767/231444263-4b8b314c-9320-478c-a85c-0a1848d6ac3c.mov

### LINKED ISSUE #605: Black screen appears on some android phones after scanning QR Code in mobile_scanner Version 3.1.1 and Flutter 3.7.12

### LINKED ISSUE #1002: I need to use the scanner in two places...
but when I use different instances on each view, it seems like there are some resources that are shared so I need to properly handle the start/stop and disposal of resources. I get "start() already called" (even I stop it on the other view) and other problems (stops scanning).

This is my setup:
A bottom bar with three buttons, opening three views.

Left bottom bar button: a view with a button. Pressing the button it pushes the scanner. Then the user can press 'back' back to the view, disposing the scanner.
Middle bottom bar button: shows the scanner, which the user can use right away. (it never disposes as it's in the bottom bar)

How do I manage the resources just so I can have the set up I mentioned? One instance will never dispose, and the other will come in and out.

### LINKED ISSUE #1091: Error: Called start() while already started!
Hi,
@navaronbracke 

What could be the reason of this error in the ErrorBuilder?
`Called start() while already started!`

It doesn't happen all the times, it happens for example when I restart the app when I was in a screen that is using the MobileScanner, and open the screen again.

Mostly happens in Debug mode.

I have also issues when I navigate from a screen that has a Scanner in it to a new screen with the Scanner using `push`, so in the screens stack there are multiple instances with MobileScanner.
Calling the "stop()" before doesn't help.

How can I avoid this?

How can I check if MobileScanner was already started?

How can I actually create and use multiple instances of the Scanner?

### LINKED ISSUE #1135: [Android] mobile scanner preview randomly blank when navigating to scanner widget
Hello, iam working on a scanner application and i may have found a bug with camera preview display logic.

ezgif-2-2877c977bd

In this GIF i attached at end I repeatedly navigate back and forth from main menu back to scanning window until error occurs (the scanning window being blank).

**(The layout change where it goes from 50/50 blank -> 0/100 barcode list -> 50/50 error icon is done by me with gesture that cannot be seen in the gif)**

Most of the times the camera opens without issue, but sometimes the preview is blank. **However in the blank state, it still detects barcodes that are placed in front of the camera.**

Sometimes the error occurs even after some longer duration (for example being in main menu for one minute and then going to scan widget), like there were some unreleased resources even though iam not scanning anymore.

I have placed a debug line in the mobile scanner file to try diagnose the issue, but when it occurs the error print does not trigger
```
        if (error != null) {
          const Widget defaultError = ColoredBox(
            color: Colors.black,
            child: Center(child: Icon(Icons.error, color: Colors.white)),
          );

          print('⚓♦️♦️⚓ MobileScanner: error: $error'); <--------------------------------------------

          return widget.errorBuilder?.call(context, error, child) ??
              defaultError;
        }
```

This is my init state code
```
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    unawaited(cameraController.start());

    _barcodeSubscription = cameraController.barcodes.listen((barcodes) {
      debugPrintCHD("Barcode detected: $barcodes");
      _handleBarcodeDetection(barcodes: barcodes, manualBarcode: null);
    });
    super.initState();
  }
```

And this is my widget observer code copied from example code
```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!cameraController.value.isInitialized) {
      return;
    }

    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        return;
      case AppLifecycleState.resumed:
        // Restart the scanner when the app is resumed.
        // Don't forget to resume listening to the barcode events.
        _barcodeSubscription = cameraController.barcodes.listen((barcodes) {
          debugPrintCHD("Barcode detected: $barcodes");
          _handleBarcodeDetection(barcodes: barcodes, manualBarcode: null);
        });
        unawaited(cameraController.start());
      case AppLifecycleState.inactive:
        // Stop the scanner when the app is paused.
        // Also stop the barcode events subscription.
        unawaited(_barcodeSubscription?.cancel());
        _barcodeSubscription = null;
        unawaited(cameraController.stop());
    }
  }
```

I have also tried resolving this issue by forcing camera dispose on pop like so: (didnt help though)

```
  @override
  Widget build(BuildContext context) {
    return PopScope(
      onPopInvoked: (_) async {
        if (cameraController.value.isInitialized || cameraController.value.isRunning) {
          cameraController.stop();
          await cameraController.dispose();
        }
      },
      child: Scaffold(
      ........
```

I don't have idea what could i be doing wrong, so iam creating this 'ticket'.

Any help would be appriciated, and sorry for my bad grammar 

Flutter doctor -v:
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale cs-CZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.7)
[!] Android Studio (version 2023.2)
    X Unable to find bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
PS C:\Users\avetr\AndroidStudioProjects\chydis_skener_flutter> flutter doctor -v
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale cs-CZ)
    • Flutter version 3.22.2 on channel stable at C:\flutterDev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (8 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\avetr\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34902.65
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\avetr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • 22031116BG (mobile) • SWORVKUKUW4DFUX8 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

### LINKED ISSUE #1378: Black screen on iOS
Working perfectly on Android and version 6.0.7.
On iOS, the screen is just black, but the scanner is working and I get results still. 
All permissions granted. 
How can I fix it?

[✓] Flutter (Channel stable, 3.29.2, on macOS 15.4 24E248 darwin-arm64, locale en-US) [1,932ms]
    • Flutter version 3.29.2 on channel stable at /Users/lbofhn/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (4 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1,688ms]
    • Android SDK at /Users/lbofhn/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Users/lbofhn/homebrew/opt/openjdk@17/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.14+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,820ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] VS Code (version 1.99.1) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (7 available) [5.8s]
    • Pixel 9 (mobile)                    • 46140DLAQ006TU                       • android-arm64  • Android 15 (API 35)
    • sdk gphone64 arm64 (mobile)         • emulator-5554                        • android-arm64  • Android 15 (API 35) (emulator)
    • Ludwig – iPhone (wireless) (mobile) • 00008120-000808921128C01E            • ios            • iOS 18.3.2 22D82
    • iPhone 16 Plus (mobile)             • B68A258F-8E41-41AB-B0BF-59DDE1DDE119 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-3 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.4 24E248 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.4 24E248 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 135.0.7049.85

[✓] Network resources [1,579ms]
    • All expected network resources are available.

### PR DESCRIPTION
**Pull request by juliansteenbakker**
Fixes #1378
Fixes #1135
Fixes #493 
Fixes #589
Fixes #605 
Fixes #1002
Fixes #1135

Part of #1091, except hot-reloading, which will be fixed in another PR.

This PR fixes the black screen issue, which is caused when the controller is started multiple times (and thus is running), and a piece of code that stops subsequent controller initalization, leaving it uninitialized, and without error message.

The root cause of multiple controllers being started is most likely due to the start() and stop() methods not being awaited for, causing improper controller states. The initialization of the default controller is changed so that async functions are awaited for. 

Users should check their own implementation if a custom controller is being used. This PR makes it easier to discover this because proper error messages are now being shown. (only if kDebugMode = true, otherwise it defaults to a generic error message)

### CODE REVIEW

File: lib/src/mobile_scanner.dart [hunk 1]
```diff
@@ -270,31 +282,39 @@ class _MobileScannerState extends State<MobileScanner>
...
+      await controller.dispose();
+      WidgetsBinding.instance.removeObserver(this);
     }
+  }
+
+  @override
+  void initState() {
     super.initState();
+    controller = widget.controller ?? MobileScannerController();
+    initController();
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:305]:
```suggestion
    unawaited(initController());
```

File: lib/src/mobile_scanner.dart [hunk 2]
```diff
@@ -270,31 +282,39 @@ class _MobileScannerState extends State<MobileScanner>
...
       _subscription!.cancel();
       _subscription = null;
     }
 
-    if (controller.autoStart) {
-      controller.stop();
-    }
-    // When this widget is unmounted, reset the scan window.
-    unawaited(controller.updateScanWindow(null));
+    disposeCamera();
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:315]: Do we need to await this method, per your comment in the PR description?
If so, then `super.dispose()` should go first, otherwise you'll hit an assert across the async gap (been there done that :p ) Or we can wrap this in `unawaited`

File: lib/src/mobile_scanner.dart [hunk 3]
```diff
@@ -270,31 +282,39 @@ class _MobileScannerState extends State<MobileScanner>
...
+
+  Future<void> disposeCamera() async {
+    if (controller.autoStart) {
+      await controller.stop();
+    }
+
+    // Dispose default controller if not provided by user
+    if (widget.controller == null) {
+      await controller.dispose();
+      WidgetsBinding.instance.removeObserver(this);
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:297]: Shouldn't we have `WidgetsBinding.instance.removeObserver(this);` done first in this method? What if either stop or dispose fails, then we leak a listener?

**Review by navaronbracke — CHANGES_REQUESTED** [review]

**Comment by navaronbracke** [comment]
@juliansteenbakker One small Github related nit, you'll have to put the fixed issues on separate "Fixes #<number>" lines, or it won't pick them all up.

File: lib/src/objects/scanner_error_widget.dart [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+            const Padding(
+              padding: EdgeInsets.only(bottom: 16),
+              child: Icon(Icons.error, color: Colors.white),
+            ),
+            if (kDebugMode) ...[
+            Text(
+              error.errorCode.message,
+              style: const TextStyle(color: Colors.white),
+            ),
+            if (error.errorDetails != null) Text(
```
[the remark this answers is not in the document]
Comment (juliansteenbakker) [reply lib/src/objects/scanner_error_widget.dart:27]: Did not know about the If-case syntax, cool!

File: lib/src/mobile_scanner.dart [hunk 5]
```diff
@@ -207,12 +209,9 @@ class _MobileScannerState extends State<MobileScanner>
         }
 
         final MobileScannerException? error = value.error;
-
+        // If the controller encountered, show an error screen, or user provided placeholder
```
[the remark this answers is not in the document]
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart:212]: Bad comment from older code, i'll remove it

File: lib/src/mobile_scanner.dart [hunk 6]
```diff
@@ -270,31 +282,39 @@ class _MobileScannerState extends State<MobileScanner>
...
     super.initState();
+    controller = widget.controller ?? MobileScannerController();
+    initController();
   }
 
   @override
   void dispose() {
-    super.dispose();
-
     if (_subscription != null) {
```
[the remark this answers is not in the document]
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart:310]: Since it's an async function, i think it's better to move it to the other async functions in dispose. Will update the function.

File: lib/src/mobile_scanner.dart (hunk 3 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart:297]: Yeah that does not seem right. I have a feeling it is already leaking if the user provides its own controller.

**Comment by juliansteenbakker** [comment]
> @juliansteenbakker One small Github related nit, you'll have to put the fixed issues on separate "Fixes #" lines, or it won't pick them all up.

thanks for the tip!

I've added the requested changes, thanks for verifying!

File: lib/src/mobile_scanner.dart (hunk 2 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart]: The problem is that if everything is unawaited, race conditions can occur due to the native part receiving multiple calls without waiting for closure. I've changed `super.dispose()` to be on top of the function, and everything seems to be working good right now.

**Comment by navaronbracke** [comment]
@juliansteenbakker Sorry if I explained it wrong, but each issue number needs to have the word "fix"/"fixes" in front of it.
I updated the OP to fix that. Also, for the issue that is partially fixed, I updated the wording so Github doesn't auto-close it yet ("partially fixes" still contains the word "fixes")

File: lib/src/mobile_scanner.dart [hunk 7]
```diff
@@ -270,33 +280,37 @@ class _MobileScannerState extends State<MobileScanner>
...
+  void initState() {
+    super.initState();
+    controller = widget.controller ?? MobileScannerController();
+    unawaited(initMobileScanner());
+  }
+
+  @override
+  void dispose() {
+    super.dispose();
+    disposeMobileScanner();
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:311]: Should we use unawaited here? (like in initState for the setup?)

```suggestion
    unawaited(disposeMobileScanner());
```

File: lib/src/mobile_scanner.dart [hunk 8]
```diff
@@ -270,33 +280,37 @@ class _MobileScannerState extends State<MobileScanner>
...
-  @override
-  void dispose() {
-    super.dispose();
-
-    if (_subscription != null) {
-      _subscription!.cancel();
-      _subscription = null;
-    }
+  Future<void> disposeMobileScanner() async {
+    await _subscription?.cancel();
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:288]: I would move the WidgetsBinding observer call to the font? Also, null-out the subscription?

```suggestion
  Future<void> disposeMobileScanner() async {
    if (widget.controller == null) {
      WidgetsBinding.instance.removeObserver(this);
    }
  
    await _subscription?.cancel();
    _subscription = null;
    
    if (controller.autoStart) {
      await controller.stop();
    }
    
    // Dispose default controller if not provided by user
    if (widget.controller == null) {
      await controller.dispose();
    }    
  }
```

**Comment by juliansteenbakker** [comment]
> @juliansteenbakker Sorry if I explained it wrong, but each issue number needs to have the word "fix"/"fixes" in front of it. I updated the OP to fix that. Also, for the issue that is partially fixed, I updated the wording so Github doesn't auto-close it yet ("partially fixes" still contains the word "fixes")

Thanks for clarification, i see they are linked now. If everything is alright i'll merge this.

**Review by navaronbracke — CHANGES_REQUESTED** [review]

**Comment by navaronbracke** [comment]
@juliansteenbakker fyI: we should also get this change onto the dev branch after this is merged.

File: lib/src/mobile_scanner.dart (hunk 8 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart:288]: I didn't null it out, because in the `didChangeAppLifecycleState` function, `case AppLifecycleState.inactive:` also doesn't null it out because of syncronous commands. However, maybe we need to create a separate async function for that aswell.

Ultimately it's not really a good pattern of using async methods in `dispose` and `didChangeAppLifecycleState`, but because we are handling a lot on the native side, there isn't really any better option for now. We can look into it for the new major release, or even the next one after that.

**Comment by juliansteenbakker** [comment]
> @juliansteenbakker fyI: we should also get this change onto the dev branch after this is merged.

Yeah that's gonna be the next thing i wanna do, after #1393 gets merged

File: lib/src/mobile_scanner.dart [hunk 9]
```diff
@@ -270,33 +280,41 @@ class _MobileScannerState extends State<MobileScanner>
...
 
-  @override
-  void dispose() {
-    super.dispose();
-
-    if (_subscription != null) {
-      _subscription!.cancel();
-      _subscription = null;
+  Future<void> disposeMobileScanner() async {
+    if (widget.controller == null) {
```
Comment (juliansteenbakker) [inline lib/src/mobile_scanner.dart:288]: @navaronbracke i don't think we need to change the check here to the same as where `addObserver` is called on https://github.com/juliansteenbakker/mobile_scanner/blob/7b5b2bc9607090de150128d82fb460ca999e5876/lib/src/mobile_scanner.dart#L275

Comment (navaronbracke) [reply lib/src/mobile_scanner.dart:288]: I agree that the add/ remove of the observer should happen under the same conditions.
So if `onDetect` is set or if the user didn't provide a controller we add/ remove the internal observer?

File: lib/src/mobile_scanner.dart (hunk 8 above)
Comment (navaronbracke) [reply lib/src/mobile_scanner.dart:292]: Yeah, async dispose/initState/didChangeAppLifecycleState is meh. So I'd rather go with wrapping them in `unawaited` then.

**Review by navaronbracke — APPROVED** [review]
LGTM, if the WidgetsBindingObserver will be removed correctly like you mentioned.

File: lib/src/mobile_scanner.dart (hunk 9 above)
Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart]: Yeah, now i look closer to it, i think it's better to change `widget.onDetect != null` to `widget.controller == null`, because if `widget.controller == null`, `widget.onDetect` shouldn't really be null, because that would leave the barcode scanner in a camera state without any options to catch a result. We could even add an assert, that always a controller or onDetect is provided.

Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart]: The observer in `mobile_scanner` is simply to pause and resume `onDetect` if provided. It doesn't really matter if a controller is also provided or not, the stream should still be paused and resumed. Only when a user doesn't provide `onDetect`, and relies on the own provided `MobileScannerController` to listen to the stream, the `observer` isn't used.

So in short, i don't think we need a check for `widget.controller == null`

Comment (juliansteenbakker) [reply lib/src/mobile_scanner.dart]: We could also just let the subscription be active, even when AppLifecycleState changes, and just leave `controller.start()` and `controller.stop()`.

Comment (navaronbracke) [reply lib/src/mobile_scanner.dart]: > We could also just let the subscription be active, even when AppLifecycleState changes, and just leave `controller.start()` and `controller.stop()`.

That is fine too.

**Comment by navaronbracke** [comment]
That was added to fix https://github.com/juliansteenbakker/mobile_scanner/issues/1210
Since with `onDetect` you have a StreamSubscription without an error handler otherwise, and unhandled errors from a Stream bubble up. So I just added an empty error handler, while allowing users to provide their own.

**Comment by juliansteenbakker** [comment]
> That was added to fix #1210 Since with `onDetect` you have a StreamSubscription without an error handler otherwise, and unhandled errors from a Stream bubble up. So I just added an empty error handler, while allowing users to provide their own.

Gotya!
