### PR TITLE
fix: provide correct initial torch state

### LINKED ISSUE #1033: iOS / MacOS wrongly map torchMode index 2 to "unavailable"
mobile_scanner: ^5.0.0

Torch state is by default unavailable and I am not able to turn on/off the flashlight, if i initialise the controller with torchEnabled as true, then I could turn it off/on. Is it not possible for torch be in off state and on enabling changing to on state.

```
class Scan extends StatefulWidget {
  const Scan({super.key});

  @override
  State<Scan> createState() => _ScanState();
}

class _ScanState extends State<Scan>
    with WidgetsBindingObserver {
  MobileScannerController cameraController = MobileScannerController();

  @override
  void initState() {
    super.initState();
    cameraController.start();
  }

  @override
  void dispose() async {
    super.dispose();
    await cameraController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          const SizedBox(
            height: 20,
          ), 
          ValueListenableBuilder(
            valueListenable: cameraController,
            builder: (context, state, child) {
              if (!state.isInitialized || !state.isRunning) {
                return const SizedBox.shrink();
              }
              switch (state.torchState) {
                case TorchState.off:
                  return IconButton(
                    icon: const Icon(
                      Icons.flash_off,
                      color: Colors.grey,
                    ),
                    iconSize: 32.0,
                    onPressed: () async {
                      await cameraController.toggleTorch();
                    },
                  );
                case TorchState.on:
                  return IconButton(
                    icon: const Icon(
                      Icons.flash_on,
                      color: Colors.yellow,
                    ),
                    iconSize: 32.0,
                    onPressed: () async {
                      await cameraController.toggleTorch();
                    },
                  );
                case TorchState.unavailable:
                  return const Icon(
                    Icons.no_flash,
                    color: Colors.black,
                  );
              }
            },
          ),
        ],
      ),
    );
  }
}
```

### LINKED ISSUE #1041: torchState Inverted after using toggleTorch
After Upgrading from 4.0.1 to 5.0.1 torchState is Inverted after using toggleTorch.

I am calling: 
await controller.toggleTorch();
final state =  controller.value.torchState

torchState is on when my device flash is off and off when my device is on. 

tested on android 13, POCO X5 PRO

 flutter doctor -v
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [versÆo 10.0.22631.3447], locale pt-BR)
    • Flutter version 3.19.6 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\....\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\....\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (4 available)
    • 22101320I (mobile) • e6f01007 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [versÆo 10.0.22631.3447]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 124.0.6367.61
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 123.0.2420.97

[√] Network resources
    • All expected network resources are available.

• No issues found!

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1041
Fixes #1033

### CODE REVIEW

File: ios/Classes/MobileScannerUtilities.swift [hunk 1]
```diff
@@ -8,31 +8,6 @@ extension CVBuffer {
         let cgImage = CIContext().createCGImage(ciImage, from: ciImage.extent)
         return UIImage(cgImage: cgImage!)
     }
-
```
Comment (navaronbracke) [inline ios/Classes/MobileScannerUtilities.swift:11]: This was unused old code

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt [hunk 2]
```diff
@@ -167,7 +168,7 @@ class MobileScannerHandler(
         val position =
             if (facing == 0) CameraSelector.DEFAULT_FRONT_CAMERA else CameraSelector.DEFAULT_BACK_CAMERA
 
-        val detectionSpeed: DetectionSpeed = DetectionSpeed.values().first { it.intValue == speed}
+        val detectionSpeed: DetectionSpeed = DetectionSpeed.entries.first { it.intValue == speed}
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:171]: `values()` is deprecated in Kotlin 1.9
