### PR TITLE
fix: correct android preview orientation

### LINKED ISSUE #1319: 7.0.0-beta.6: Incorrect camera preview orientation
Using 7.0.0-beta.6 (and Flutter 3.27.0), in my limited testing, the camera preview orientation is incorrect.

The below table lists the camera preview rotation, in degrees, for the different device orientations:
| Device | OS | Portrait Up | Portrait Upside Down | Landscape Left | Landscape Right |
| - | - | - | - | - | - |
| iPad (8th generation) | iPadOS 18.0.1 | +90 | -90 | ±180 | 0 |
| Pixel 6a | Android 15 | -90 | N/A | 0 | ±180 |

The definition of landscape left vs right seems fuzzy. My definitions for the above table are as follows:
- **Landscape Left**: device rotated left from portrait up (e.g. home button on the right)
- **Landscape Right**: device rotated right from portrait up (e.g. home button on the left)

I would expect the rotation to be 0 in all cases, i.e. that the plugin handles this and automatically rotates the camera preview.

I am aware of https://github.com/juliansteenbakker/mobile_scanner/discussions/17.

Will this be resolved with 7.0.0?

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR adjusts the preview orientation for Android.

Previously the formula was not entirely correct.

Fixes #1319

### CODE REVIEW

**Comment by camsim99** [comment]
Thanks for testing! What device are you testing on for `handlesCropAndRotation` is true? And is it an emulator? Either way, I agree; that would be a separate bug that is not camera-specific.

I don't know if naturally landscape oriented devices will work yet but if it does, that'd be a happy surprise, so let me know.

**Comment by navaronbracke** [comment]
I was testing on this device, which is running Android 13: https://www.gsmarena.com/samsung_galaxy_xcover6_pro-11600.php

I did not test emulators, since I know that those might not be working properly yet.
I'll try to see if I can find a tablet to test on as well.

**Comment by navaronbracke** [comment]
Also, the Motorola had its Vulkan support fixed in Flutter 3.29, but I doubt that that is related, as it still reports `handlesCropAndRotation: true`, which indicates it is using the old API under the hood.

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt [hunk 1]
```diff
@@ -621,7 +638,7 @@ class MobileScanner(
         }
         val paint = Paint().apply { colorFilter = ColorMatrixColorFilter(colorMatrix) }
 
-        val invertedBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, bitmap.config)
+        val invertedBitmap = Bitmap.createBitmap(bitmap.width, bitmap.height, bitmap.config!!)
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt:641]: This is a change that wasn't surfaced when using Kotlin 1.7, hence the bump to Kotlin 1.8

File: example/pubspec.yaml [hunk 2]
```diff
@@ -19,7 +19,7 @@ dependencies:
   flutter:
     sdk: flutter
 
-  image_picker: ^1.0.4
```
Comment (navaronbracke) [inline example/pubspec.yaml:22]: Bumping image picker (and updating the pubspec.lock locally) fixed a build issue with the removal of the Android v1 embedding.

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt [hunk 3]
```diff
@@ -191,7 +191,7 @@ class MobileScannerHandler(
                         "textureId" to it.id,
                         "size" to mapOf("width" to it.width, "height" to it.height),
                         "naturalDeviceOrientation" to it.naturalDeviceOrientation,
-                        "isPreviewPreTransformed" to it.isPreviewPreTransformed,
+                        "handlesCropAndRotation" to it.handlesCropAndRotation,
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:194]: Renamed to match the actual name from the SurfaceProducer API.

File: example/android/.gitignore [hunk 4]
```diff
@@ -11,3 +11,5 @@ GeneratedPluginRegistrant.java
 key.properties
 **/*.keystore
 **/*.jks
+
+**/.cxx
```
Comment (navaronbracke) [inline example/android/.gitignore:15]: I had to add this line, since Flutter 3.29 would add a .cxx folder when compiling on Android. New `flutter create`d templates did include a change like this, too.

File: lib/src/method_channel/mobile_scanner_method_channel.dart [hunk 5]
```diff
@@ -356,7 +365,6 @@ class MethodChannelMobileScanner extends MobileScannerPlatform {
 
     _textureId = null;
     _pausing = false;
-    _surfaceProducerDelegate?.dispose();
```
Comment (navaronbracke) [inline lib/src/method_channel/mobile_scanner_method_channel.dart:359]: The disposal of the "delegate" is no longer needed, since the stream subscription is moved to a widget.

File: lib/src/method_channel/mobile_scanner_method_channel.dart [hunk 6]
```diff
@@ -319,9 +331,6 @@ class MethodChannelMobileScanner extends MobileScannerPlatform {
         startResult,
         cameraDirection,
       );
-      _surfaceProducerDelegate?.startListeningToDeviceOrientation(
```
Comment (navaronbracke) [inline lib/src/method_channel/mobile_scanner_method_channel.dart:322]: This is now handled by a separate widget.

File: lib/src/method_channel/rotated_preview.dart [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+
+  @override
+  Widget build(BuildContext context) {
+    final double rotation = _computeRotation(
+      deviceOrientation,
+      sensorOrientationDegrees: widget.sensorOrientationDegrees,
+      sign: widget.facingSign,
+    );
+
+    // FIXME: Can this be improved?
```
Comment (juliansteenbakker) [inline lib/src/method_channel/rotated_preview.dart:125]: I don't think there is a better way to handle this right?

**Review by juliansteenbakker — APPROVED** [review]

File: lib/src/method_channel/rotated_preview.dart (hunk 7 above)
Comment (navaronbracke) [reply lib/src/method_channel/rotated_preview.dart:125]: I agree. I think it is fine to remove the comment here. We can always revisit this specific code if needed.
