### PR TITLE
fix: Fix discrepancy between barcode bounding box and barcode capture size

### LINKED ISSUE #1162: barcodeCapture.size.isEmpty is always true on Android
I've setup the following widget to use it as QR-Code Scanner Screen:

```
dummy.dart:


import 'dart:async';
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

part 'dummy_window.dart';

/// Creates a QR-Code Scanner with an inner frame within which scanned QR Codes
/// will be captured
class QRCodeScannerScreen extends StatefulWidget {

  const QRCodeScannerScreen({
    super.key,
  });

  @override
  State<QRCodeScannerScreen> createState() => _QRCodeScannerScreenState();
}

/// Mixin the [WidgetsBindingObserver] to bind lifecycle changes to the
/// functionality of the code scanner
/// (see https://pub.dev/packages/mobile_scanner#usage)
class _QRCodeScannerScreenState extends State<QRCodeScannerScreen>
    with WidgetsBindingObserver {
  /// Controller needed to produce QR-Code scanning ability via the
  /// 'mobile_scanner' flutter package
  /// (see https://pub.dev/packages/mobile_scanner#usage)
  final MobileScannerController _controller = MobileScannerController(
    // Avoid that QR-code is scanned an excessive amount of times
      detectionSpeed: DetectionSpeed.normal,
      // Wait for 750 ms before scanning again
      // Leave this, as this is what prevented android scans from working on
      // older devices
      detectionTimeoutMs: 250,
      // Use backwards camera
      facing: CameraFacing.back,
      // Disable flashlight on start
      torchEnabled: false,
      formats: const [BarcodeFormat.qrCode]
  );

  /// Providing a stream subscription is necessary to be able to subscribe a
  /// listener to the scanner of barcodes
  /// (see https://pub.dev/packages/mobile_scanner#usage)
  StreamSubscription<Object?>? _subscription;

  /// Callback which reacts to a properly captured barcode by the scanner within
  /// the borders of the scan window, by in that case exiting the screen with
  /// the value of the first returned barcode, as string
  ///
  /// see the [ValueListenableBuilder] and the [StreamBuilder] within the
  /// file https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart
  void _handleCapturedBarcode(BarcodeCapture barcodeCapture) {

    print("captured");

    print("mounted: $mounted");
    print("_controller.value.isInitialized: ${_controller.value.isInitialized}");
    print("_controller.value.isRunning: ${_controller.value.isRunning}");
    print("_controller.value.error: ${_controller.value.error}");
    print("barcodeCapture.barcodes.isNotEmpty: ${barcodeCapture.barcodes.isNotEmpty}");
    print("barcodeCapture.barcodes.firstOrNull: ${barcodeCapture.barcodes.firstOrNull}");
    print("barcodeCapture.barcodes.first.corners.isNotEmpty: ${barcodeCapture.barcodes.first.corners.isNotEmpty}");
    print("!_controller.value.size.isEmpty: ${!_controller.value.size.isEmpty}");
    print("!barcodeCapture.size.isEmpty: ${!barcodeCapture.size.isEmpty}");
    print("barcodeCapture.barcodes.first.rawValue: ${barcodeCapture.barcodes.first.rawValue}");

    if (mounted &&

        /// If the [MobileScannerState] is initialized
        _controller.value.isInitialized &&

        /// If the [MobileScannerState] is running
        _controller.value.isRunning &&

        /// If the [MobileScannerState] currently has no errors
        _controller.value.error == null &&

        /// If at least one result is captured
        barcodeCapture.barcodes.isNotEmpty &&

        /// If an actual barcode was returned
        barcodeCapture.barcodes.firstOrNull != null &&

        /// If the corners of the barcode can all be found (= they are all
        /// situated within the scanner window of the [MobileScanner] being used
        barcodeCapture.barcodes.first.corners.isNotEmpty &&

        /// If the size of the camera output is not empty
        !_controller.value.size.isEmpty &&

        /// If the size of the scanned barcode can be detected
        !barcodeCapture.size.isEmpty) {
      /// As soon as a code has been properly detected, cancel the stream
      /// subscription, such that this will not be called again (otherwise,
      /// experienced that the app called Navigator.pop() multiple times in
      /// sequence).
      _subscription?.cancel();
      _subscription = null;
      Navigator.pop(
        context,
        barcodeCapture.barcodes.first.rawValue,
      );
    }
  }

  /// Adapt the behaviour of the [_controller] and the [_subscription] according
  /// to the current [AppLifecycleState]
  /// (see https://pub.dev/packages/mobile_scanner#usage)
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    /// If the controller is not ready, do not try to start or stop it.
    /// Permission dialogs can trigger lifecycle changes before the controller is ready.
    if (!_controller.value.isInitialized) {
      return;
    }

    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        return;
      case AppLifecycleState.resumed:

      /// Restart the scanner when the app is resumed.
      /// Don't forget to resume listening to the barcode events.
        _subscription = _controller.barcodes.listen(_handleCapturedBarcode);

        unawaited(_controller.start());
      case AppLifecycleState.inactive:

      /// Stop the scanner when the app is paused.
      /// Also stop the barcode events subscription.
        unawaited(_subscription?.cancel());
        _subscription = null;
        unawaited(_controller.stop());
    }
  }

  @override
  void initState() {
    _controller.stop();

    super.initState();

    /// Start everything related to the scanner upon startup
    /// (see https://pub.dev/packages/mobile_scanner#usage)
    /// Start listening to lifecycle changes.
    WidgetsBinding.instance.addObserver(this);

    /// Start listening to the barcode events.
    _subscription = _controller.barcodes.listen(_handleCapturedBarcode);

    /// Finally, start the scanner itself.
    unawaited(_controller.start());

  }

  /// Dispose of anything related to the scanner state upon dispose
  /// (see https://pub.dev/packages/mobile_scanner#usage)
  @override
  Future<void> dispose() async {
    /// Stop listening to lifecycle changes.
    WidgetsBinding.instance.removeObserver(this);

    /// Stop listening to the barcode events.
    unawaited(_subscription?.cancel());
    _subscription = null;

    /// Dispose the widget itself.
    super.dispose();

    /// Finally, dispose of the controller.
    await _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    /// Build a squared Y x Y QR-Code Scanner Window
    final scanWindow = Rect.fromCenter(
      center: MediaQuery.sizeOf(context).center(Offset.zero),
      width: 250,
      height: 250,
    );

    final double spacingOfInstructionLabelFromTheTop =
        MediaQuery.of(context).size.height * 0.1;

    final Widget screenContent = Stack(
      fit: StackFit.expand,
      children: [
        /// QR-Code Scanner
        MobileScanner(
          /// To make sure that the entire screen is covered
          fit: BoxFit.contain,

          /// Controller of the Mobile Scanner, to bind the controller to the
          /// Stream returning the scanned barcodes upon scan
          controller: _controller,

          /// Such that the barcode scanner will only scan codes which intersect
          /// with this rectangle
          scanWindow: scanWindow,

          /// Callback used to generate the content to be shown upon an error
          errorBuilder: (context, exception, _) {
            /// To resolve issue with error saying 'called start() while
            /// already started',
            /// see https://github.com/juliansteenbakker/mobile_scanner/issues/539
            _controller.stop();
            _controller.start();

            return const Text('Error');
          },
        ),

        /// Overlay with the provided [scanWindow] cut out
        _QRCodeScannerWindow(
          scanWindow: scanWindow,
          controller: _controller,
        ),

        /// Label present above the square of the QR-Code Scanner, providing the
        /// instruction to place the code to be scanner within the frame
        Align(
          alignment: Alignment.topCenter,
          child: Padding(
            padding: EdgeInsets.fromLTRB(
              50,
              spacingOfInstructionLabelFromTheTop,
              50,
              spacingOfInstructionLabelFromTheTop / 2,
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              mainAxisSize: MainAxisSize.max,
              children: [
                /// Use expanded + softWrap: true to wrap text if it exceeds
                /// the screen length
                Expanded(
                  child: Text(
                    AppLocalizations.of(context).pleasePlaceQRCodeWithinSquare,
                    textAlign: TextAlign.center,
                    softWrap: true,
                  ),
                ),
              ],
            ),
          ),
        )
      ],
    );

    return Scaffold(
      appBar: AppBar(
        title: Text(
          AppLocalizations.of(context).qrScannerTitle,
        ),
      ),
      body: screenContent,
    );

  }
}


dummy_window.dart:

part of 'dummy.dart';

/// Painter used to generate the [_QRCodeScannerWindow] widget
class _QRCodeScannerPainter extends CustomPainter {
  /// Rectangle within which the scanning will be active
  final Rect scanWindow;

  const _QRCodeScannerPainter({
    required this.scanWindow,
  });

  /// Method used to paint the overlay, to create a not-entirely opaque screen
  /// overlay with a rectangle cut out in the center of it, according to the
  /// passed [scanWindow]
  @override
  void paint(Canvas canvas, Size size) {
    /// Background Paint, which is simply an overlay that covers the entire
    /// screen
    final backgroundPath = Path()
      ..addRect(
        Rect.largest,
      );

    /// Path to be cut out from the overlay
    final cutoutPath = Path()
      ..addRect(
        scanWindow,
      );

    /// Create the final Paint, corresponding to the semi-transparent overlay
    /// with the passed [scanWindow] cut out, which will finally result in an
    /// overlay screen with the inner rectangle cut out, representing the
    /// scanners' window
    final resultingPath =
    Path.combine(PathOperation.difference, backgroundPath, cutoutPath);

    /// Create the black semi-transparent pain to be applied to
    /// [resultingPath]
    final backgroundPaint = Paint()
      ..color = Colors.black.withOpacity(
        0.75,
      )
      ..style = PaintingStyle.fill
      ..blendMode = BlendMode.dstOut;

    /// Draw the [resultingPath] with the [backgroundPaint] applied onto it by
    /// drawing it into the canvas
    canvas.drawPath(
      resultingPath,
      backgroundPaint,
    );

    /// Create additional paint for the border of the cutout rectangle
    final borderPaint = Paint()
      ..color = Colors.white
      ..style = PaintingStyle.stroke
      ..strokeWidth = 3.0;

    canvas.drawRect(
      scanWindow,
      borderPaint,
    );
  }

  /// A repaint is never required
  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}

/// Scanner Window Overlay used for the QR-Code Scanner Screen, to frame the
/// contents being scanned by the scanner
class _QRCodeScannerWindow extends StatelessWidget {
  /// controller of the [MobileScanner] used for the [QRCodeScannerScreen]
  final MobileScannerController controller;

  /// Rectangle within which the scanning will be active
  final Rect scanWindow;

  const _QRCodeScannerWindow({
    required this.controller,
    required this.scanWindow,
  });

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: controller,
      builder: (context, value, child) {
        // Not ready.
        if (!value.isInitialized ||
            !value.isRunning ||
            value.error != null ||
            value.size.isEmpty) {
          return const SizedBox();
        }

        return CustomPaint(
          painter: _QRCodeScannerPainter(
            scanWindow: scanWindow,
          ),
        );
      },
    );
  }
}
```

Only on physical android devices (both a modern and an older one), the screen is never left. That's why I've added the many print statements in the code, and indeed, for android only, `barcoeCapture.size.isEmpty` is always `true`, so the screen is never exit on Android phones. A sample output of all the print statements is:

```
I/flutter (25114): captured
I/flutter (25114): mounted: true
I/flutter (25114): _controller.value.isInitialized: true
I/flutter (25114): _controller.value.isRunning: true
I/flutter (25114): _controller.value.error: null
I/flutter (25114): barcodeCapture.barcodes.isNotEmpty: true
I/flutter (25114): barcodeCapture.barcodes.firstOrNull: Instance of 'Barcode'
I/flutter (25114): barcodeCapture.barcodes.first.corners.isNotEmpty: true
I/flutter (25114): !_controller.value.size.isEmpty: true
I/flutter (25114): !barcodeCapture.size.isEmpty: false <-- This seems to be the problem
I/flutter (25114): barcodeCapture.barcodes.first.rawValue: properly detected URL
```

on iOS, no problem at all. 

Any idea why this could be happening?

Version we're using: `mobile_scanner: ^5.1.1`

flutter doctor output:

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR fixes a discrepancy between what is meant with the bounding box of a scanned barcode and the size of the barcode capture output image.

It also adds the following changes:
- Added support for `returnImage` on MacOS
- Fixes a bug where `returnImage` set to false would not do anything on iOS
- Cleans up some unused code and refactors some control flow to use early returns

Fixes #1162 

cc @fulstadev

### CODE REVIEW

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt [hunk 1]
```diff
@@ -50,9 +50,11 @@ class MobileScannerHandler(
             barcodeHandler.publishEvent(mapOf(
                 "name" to "barcode",
                 "data" to barcodes,
-                "image" to image,
-                "width" to width!!.toDouble(),
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt:54]: Since the `width/height` is only for the image, I put them in a Map for the image data

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerUtilities.kt [hunk 2]
```diff
@@ -28,12 +28,22 @@ fun Image.toByteArray(): ByteArray {
 
 val Barcode.data: Map<String, Any?>
     get() = mapOf(
-        "corners" to cornerPoints?.map { corner -> corner.data }, "format" to format,
-        "rawBytes" to rawBytes, "rawValue" to rawValue, "type" to valueType,
-        "calendarEvent" to calendarEvent?.data, "contactInfo" to contactInfo?.data,
-        "driverLicense" to driverLicense?.data, "email" to email?.data,
-        "geoPoint" to geoPoint?.data, "phone" to phone?.data, "sms" to sms?.data,
-        "url" to url?.data, "wifi" to wifi?.data, "displayValue" to displayValue
+        "calendarEvent" to calendarEvent?.data,
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerUtilities.kt:31]: I sorted these properties alphabetically, to make it easier to follow. The line `"size" to boundingBox?.size,` is new.

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerUtilities.kt [hunk 3]
```diff
@@ -92,4 +102,14 @@ private val Barcode.UrlBookmark.data: Map<String, Any?>
     get() = mapOf("title" to title, "url" to url)
 
 private val Barcode.WiFi.data: Map<String, Any?>
-    get() = mapOf("encryptionType" to encryptionType, "password" to password, "ssid" to ssid)
\ No newline at end of file
+    get() = mapOf("encryptionType" to encryptionType, "password" to password, "ssid" to ssid)
+
+private val Rect.size: Map<String, Any?>
+    get() {
+        // Rect.isValid can't be accessed for some reason, so just do the check manually.
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerUtilities.kt:109]: When inspecting the source code of `android.graphics.Rect`, there was an isValid() method, but I could not access it. So I just took the check from there.

File: ios/Classes/MobileScanner.swift [hunk 4]
```diff
@@ -25,9 +25,6 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
     /// Barcode scanner for results
     var scanner = BarcodeScanner.barcodeScanner()
 
-    /// Return image buffer with the Barcode event
-    var returnImage: Bool = false
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:29]: This was moved

File: ios/Classes/MobileScanner.swift [hunk 5]
```diff
@@ -127,7 +124,6 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
     /// Gets called when a new image is added to the buffer
     public func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
         guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else {
-            print("Failed to get image buffer from sample buffer.")
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:130]: This print doesn't add any value

File: ios/Classes/MobileScanner.swift [hunk 6]
```diff
@@ -160,7 +156,9 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
                     
                     if (error == nil && barcodesString != nil && newScannedBarcodes != nil && barcodesString!.elementsEqual(newScannedBarcodes!)) {
                         return
-                    } else if (newScannedBarcodes?.isEmpty == false) {
+                    }
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:159]: Early return instead of else

File: ios/Classes/MobileScanner.swift [hunk 7]
```diff
@@ -446,17 +444,6 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
 
     var barcodesString: Array<String?>?
 
-    //    /// Convert image buffer to jpeg
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:449]: Unused

File: ios/Classes/MobileScanner.swift [hunk 8]
```diff
@@ -171,7 +169,7 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
     }
 
     /// Start scanning for barcodes
-    func start(barcodeScannerOptions: BarcodeScannerOptions?, returnImage: Bool, cameraPosition: AVCaptureDevice.Position, torch: Bool, detectionSpeed: DetectionSpeed, completion: @escaping (MobileScannerStartParameters) -> ()) throws {
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:174]: This parameter is no longer needed

File: ios/Classes/MobileScannerPlugin.swift [hunk 9]
```diff
@@ -37,24 +41,48 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin {
...
-                    if (MobileScannerPlugin.scanWindow != nil) {
-                        if (MobileScannerPlugin.isBarcodeInScanWindow(barcode: barcode, imageSize: image.size)) {
-                            return barcode.data
-                        } else {
-                            return nil
-                        }
-                    } else {
-                        return barcode.data
-                    }
+            if error != nil {
```
Comment (navaronbracke) [inline ios/Classes/MobileScannerPlugin.swift:44]: Rewriting to use early returns

File: ios/Classes/MobileScannerPlugin.swift [hunk 10]
```diff
@@ -37,24 +41,48 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin {
...
-                barcodeHandler.publishEvent(["name": "error", "data": error!.localizedDescription])
+
+                return nil
             }
+            
+            if (barcodesMap.isEmpty) {
+                return
+            }
+            
+            if (!MobileScannerPlugin.returnImage) {
```
Comment (navaronbracke) [inline ios/Classes/MobileScannerPlugin.swift:69]: This is new. Previously we would always send the image data, which is incorrect.

File: ios/Classes/MobileScannerPlugin.swift [hunk 11]
```diff
@@ -257,12 +286,14 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin {
                 DispatchQueue.main.async {
                     result(nil)
                 }
-            } else {
-                let barcodesMap: [Any?] = barcodes!.compactMap { barcode in barcode.data }
                 
-                DispatchQueue.main.async {
-                    result(["name": "barcode", "data": barcodesMap])
-                }
+                return
```
Comment (navaronbracke) [inline ios/Classes/MobileScannerPlugin.swift:290]: Early return

File: ios/Classes/MobileScannerUtilities.swift [hunk 12]
```diff
@@ -29,8 +29,27 @@ extension UIDeviceOrientation {
 
 extension Barcode {
     var data: [String: Any?] {
-        let corners = cornerPoints?.map({$0.cgPointValue.data})
-        return ["corners": corners, "format": format.rawValue, "rawBytes": rawData, "rawValue": rawValue, "type": valueType.rawValue, "calendarEvent": calendarEvent?.data, "contactInfo": contactInfo?.data, "driverLicense": driverLicense?.data, "email": email?.data, "geoPoint": geoPoint?.data, "phone": phone?.data, "sms": sms?.data, "url": url?.data, "wifi": wifi?.data, "displayValue": displayValue]
+        return [
+            "calendarEvent": calendarEvent?.data,
```
Comment (navaronbracke) [inline ios/Classes/MobileScannerUtilities.swift:33]: Like on Android, I sorted these on alphabetical keys, and added the `size`.

File: lib/src/method_channel/mobile_scanner_method_channel.dart [hunk 13]
```diff
@@ -54,31 +53,19 @@ class MethodChannelMobileScanner extends MobileScannerPlatform {
     final List<Map<Object?, Object?>> barcodes =
         data.cast<Map<Object?, Object?>>();
 
-    if (defaultTargetPlatform == TargetPlatform.macOS) {
```
Comment (navaronbracke) [inline lib/src/method_channel/mobile_scanner_method_channel.dart:57]: I updated the MacOS implementation to use the same keys / datatypes as iOS/Android. So this can be removed.

File: lib/src/method_channel/mobile_scanner_method_channel.dart [hunk 14]
```diff
@@ -54,31 +53,19 @@ class MethodChannelMobileScanner extends MobileScannerPlatform {
...
-            .toList(),
-      );
-    }
-
     if (defaultTargetPlatform == TargetPlatform.android ||
-        defaultTargetPlatform == TargetPlatform.iOS) {
-      final double? width = event['width'] as double?;
-      final double? height = event['height'] as double?;
+        defaultTargetPlatform == TargetPlatform.iOS ||
+        defaultTargetPlatform == TargetPlatform.macOS) {
```
Comment (navaronbracke) [inline lib/src/method_channel/mobile_scanner_method_channel.dart:58]: MacOS is added here, as the format has been updated to match the other platforms.

File: lib/src/method_channel/mobile_scanner_method_channel.dart [hunk 15]
```diff
@@ -54,31 +53,19 @@ class MethodChannelMobileScanner extends MobileScannerPlatform {
...
+      final Map<String, Object?>? imageData =
+          event['image'] as Map<String, Object?>?;
+      final Uint8List? image = imageData?['bytes'] as Uint8List?;
+      final double? width = imageData?['width'] as double?;
+      final double? height = imageData?['height'] as double?;
 
       return BarcodeCapture(
-        raw: data,
+        raw: event,
```
Comment (navaronbracke) [inline lib/src/method_channel/mobile_scanner_method_channel.dart:66]: MacOS used the `event` Map as raw data. This wasn't true for iOS/Android, so I updated it to match MacOS.

Unlikely that a lot of people need the raw data anyway.

File: lib/src/objects/barcode.dart [hunk 16]
```diff
@@ -38,9 +39,9 @@ class Barcode {
   factory Barcode.fromNative(Map<Object?, Object?> data) {
     final Map<Object?, Object?>? calendarEvent =
         data['calendarEvent'] as Map<Object?, Object?>?;
-    final List<Object?>? corners = data['corners'] as List<Object?>?;
```
Comment (navaronbracke) [inline lib/src/objects/barcode.dart:41]: Moved down, to be sorted on alphabetical names

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 17]
```diff
@@ -65,8 +67,6 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
             setScale(call, result)
         case "resetScale":
             resetScale(call, result)
-            //        case "analyze":
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:68]: Unused

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 18]
```diff
@@ -101,12 +101,11 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
     
     // Gets called when a new image is added to the buffer
     public func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
-        // Ignore invalid textureId
+        // Ignore invalid texture id.
         if textureId == nil {
             return
         }
         guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else {
-            print("Failed to get image buffer from sample buffer.")
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:109]: Again, a print that didn't add any value.

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 19]
```diff
@@ -127,44 +126,57 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
-                                    //                                   if barcodeType == "QR" {
-                                    //                                        let image = CIImage(image: source)
-                                    //                                        image?.cropping(to: barcode.boundingBox)
-                                    //                                        self.qrCodeDescriptor(qrCode: barcode, qrCodeImage: image!)
-                                    //                                    }
-                                }
-                            }
-                        } else {
+                        
+                        if error != nil {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:130]: Refactored to use early returns.

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 20]
```diff
@@ -127,44 +126,57 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
+                        
+                        guard let results: [VNBarcodeObservation] = request.results as? [VNBarcodeObservation] else {
+                            return
+                        }
+                        
+                        if results.isEmpty {
+                            return
+                        }
+                        
+                        let barcodes: [VNBarcodeObservation] = results.compactMap({ barcode in
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:145]: There was actually a bug here, too. MacOS would call `DispatchQueue.main.async {}` for every single barcode, instead of once, for all of them together. This has been corrected.

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 21]
```diff
@@ -127,44 +126,57 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
+                            // If there is a scan window, check if the barcode is within said scan window.
+                            if self?.scanWindow != nil && cgImage != nil && !(self?.isBarCodeInScanWindow(self!.scanWindow!, barcode, cgImage!) ?? false) {
+                                return nil
+                            }
+                            
+                            return barcode
+                        })
+                        
+                        DispatchQueue.main.async {
+                            if (!MobileScannerPlugin.returnImage) {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:155]: This is new, and similarly to iOS, we only pass the image data if requested.

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 22]
```diff
@@ -415,11 +428,6 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
         result(nil)
     }
 
-    //    func switchAnalyzeMode(_ call: FlutterMethodCall, _ result: @escaping FlutterResult) {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:418]: Unused

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 23]
```diff
@@ -504,6 +511,45 @@ class MapArgumentReader {
...
+        if !CGImageDestinationFinalize(destination) {
+            return nil
+        }
+        
+        return mutableData as Data?
+    }
+}
+
+extension VNBarcodeObservation {
+    public func toMap() -> [String: Any?] {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:545]: This is similar to the extension in the iOS implementation

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 24]
```diff
@@ -504,6 +511,45 @@ class MapArgumentReader {
 
 }
 
+extension CGImage {
+    public func jpegData(compressionQuality: CGFloat) -> Data? {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:515]: I needed this extension to get the (compressed) JPEG data from the input image.

File: lib/src/objects/barcode_capture.dart [hunk 25]
```diff
@@ -16,15 +19,21 @@ class BarcodeCapture {
   /// The list of scanned barcodes.
   final List<Barcode> barcodes;
 
-  /// The bytes of the image that is embedded in the barcode.
```
Comment (navaronbracke) [inline lib/src/objects/barcode_capture.dart:19]: Clarified a bunch of docs, that were incorrect.

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 26]
```diff
@@ -127,44 +126,57 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
+                                ])
+                                return
+                            }
+                                                        
+                            self?.sink?([
+                                "name": "barcode",
+                                "data": barcodes.map({ $0.toMap() }),
+                                "image": cgImage == nil ? nil : [
+                                    "bytes": FlutterStandardTypedData(bytes: cgImage!.jpegData(compressionQuality: 0.8)!),
+                                    "width": Double(cgImage!.width),
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:168]: The image on iOS uses doubles for width/height. On Android it uses integers, but we did convert them into doubles.

On MacOS, CGImage also uses integers, so I added a double conversion here.

File: example/ios/Runner/AppDelegate.swift [hunk 27]
```diff
@@ -1,7 +1,7 @@
 import UIKit
 import Flutter
 
-@UIApplicationMain
```
Comment (navaronbracke) [inline example/ios/Runner/AppDelegate.swift:4]: UIApplicationMain is deprecated. This was updated by the Flutter tool project migrators.
