### PR TITLE
fix: handle errors in onDetect; exclude armv7 for iOS

### LINKED ISSUE #1209: xArchive broken on iOS
This lib broke my iOS archive on Flutter 3.24.3.

When it is removed, I can archive normally. 

I'll try to do the changes proposed by [ml_kid](https://pub.dev/packages/google_ml_kit) doc. If it works, I can open a PR here to improve docs.

Otherwise you guys should do it, since there is nothing in the changelog proposing iOS changes.

Thanks for your time.

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1209 
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1210

### CODE REVIEW

File: example/ios/Podfile [hunk 1]
```diff
@@ -40,8 +40,8 @@ end
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
-        target.build_configurations.each do |config|
-          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5.0'
-        end
+    target.build_configurations.each do |config|
```
Comment (navaronbracke) [inline example/ios/Podfile:43]: This was badly indented

File: lib/src/mobile_scanner.dart [hunk 2]
```diff
@@ -34,15 +35,17 @@ class MobileScanner extends StatefulWidget {
   final MobileScannerController? controller;
 
   /// The function that signals when new codes were detected by the [controller].
-  /// If null, use the controller.barcodes stream directly to capture barcodes.
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:37]: This guidance is obsolete, as we now can handle errors in the case.
