### PR TITLE
Fix: remove observer when device is nil

### LINKED ISSUE #1395: mobile_scanner/MobileScanner.swift:341: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
Hi,

Thanks for maintaining this useful package.

mobile_scanner: ^6.0.8

I have verified the scanner on android and and iOS and i keep on getting below errors:

1. iOS: mobile_scanner/MobileScanner.swift:341: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2. Android: MobileScannerException(controllerAlreadyInitialized, The scanner was already started.)

Android error i was able to fix by stopping ad staring scanner but for iOS i cannot even catch this "mobile_scanner/MobileScanner.swift:341: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value" as an exception, my emulator just hangs. 

I know scanner is not supported in iOS emulator, but i still want to catch this exception so i can at least handle it. Currently i cannot catch this exception on iOS and therefore it always hangs my emulator app. 

Note, in iOS this exception error occurs ONLY when i run scan second time. First time I get exception (camera not supported) and second time i get fatal error i mentioned above (which does not get caught at startScan method). And I have verified multiple times to ensure resources are disposed before i re-scan but still no luck. I was wondering, if this exception can be captured so at least we can handle it via try catch.

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1395

### CODE REVIEW

File: macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 1]
```diff
@@ -481,6 +481,10 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
             return
         }
 
+        guard let device = device else {
```
Comment (navaronbracke) [inline macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:484]: MacOS also had this bug it seems

**Comment by navaronbracke** [comment]
@juliansteenbakker This will need cherry-picking to dev once merged.

**Comment by juliansteenbakker** [comment]
Thanks for the fix! Will release this at the end of today. I'm also working on a few other small fixes.
