### PR TITLE
fix: hot reload

### LINKED ISSUE #773: Better support for Hot Reload
Using Hot Reload on either iOS or Android on view with camera causes MobileScanner: Called start() while already started! error.

Repro steps:

build example app to device
open any camera screen
do Hot Reload

This problem still exists in the latest version

### LINKED ISSUE #1037: Hot restart - camera no longer usable
If i do a hot restart while camera is displayed, I no longer have the possibility to use it until app is closed.

```
MobileScannerException: code genericError, message: Called start() while already started
```

mobile_scanner: ^5.0.1

### LINKED ISSUE #1247: Permission error not reset in start/stop method
Hi ! I am developing a usecase in a Flutter APP of qr scanner via your great package. After being denied twice (permanently denied), i use openSettings() function to open settings. 

Incase i configure the camera permission, i need that my app when the lifecycle state -> resumed to start the Camera instead of displaying the ScannerErrorWidget. 
I use Cubit to maintain Permission state across App to enable dialog boxes and rebuild app as and when the state changes.

This is some of the code i have written for it:

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (!controller.value.isInitialized) {
      return;
    }

    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        return;
      case AppLifecycleState.resumed:
        if (_isReturningFromSettings) {
          _isReturningFromSettings = false;
          context.read<MobileScannerCubit>().checkCameraPermission(); // Recheck permission
        } 
          _initializeCamera();

        break;
      case AppLifecycleState.inactive:
        _isScannerDeactivated = true;
        unawaited(_subscription?.cancel());
        _subscription = null;
        unawaited(controller.stop());
    ```
    
    ```
    void _initializeCamera() {
    if (_isScannerDeactivated) return;
    
    try {
      if (!controller.value.isRunning) {
        _subscription = controller.barcodes.listen(_handleBarcode);
        unawaited(controller.start());
      }
    } catch (e) {
      logger!.d("Error initializing camera: $e");
      _deactivateCamera();
    }
  }
  ```
  
  I maintain two states understand the phase of the flow we are at a particular instance
  ```
    bool _isScannerDeactivated = false;
  bool _isReturningFromSettings = false;
  ```
  
  Cubit main functions :
  
  ```
  Future<void> checkCameraPermission() async {
    if (Platform.isAndroid || Platform.isIOS) {
        var permissionStatus = await Permission.camera.status;
        logger?.d(permissionStatus);
        if (await Permission.camera.isPermanentlyDenied) {
            emit(MobileScannerPermanentlyDeniedState());
        } else if(await Permission.camera.isDenied){
            emit(MobileScannerDeniedState());
        } else if(await Permission.camera.isGranted){
            emit(MobileScannerGrantedState());
        }
    }
  }

  Future<void> openAppPermissionSettings() async{
    openAppSettings();
  }
  
  ```
  
  Bloc Listner Code
  
  ```
  listener: (context, permissionState) {
          if (!_isDialogShowing && !_isScannerDeactivated &&  
          (permissionState is MobileScannerDeniedState || 
              permissionState is MobileScannerPermanentlyDeniedState)) {
            _isDialogShowing = true;  // Set flag before showing dialog
            _showScannerPermissionDialog(context, permissionState);
          } else if (permissionState is MobileScannerGrantedState) {
              _isScannerDeactivated = false;
              _initializeCamera();
          }
        },
        ```
        
        
        ```
  child: MobileScanner(
            controller: controller,
            onDetect: _handleBarcode,
            errorBuilder: (scannerContext, error, child) {
              String errorMessage;
              const Widget defaultError = ColoredBox(
                  color: Colors.black,
                  child: Center(child: Icon(Icons.error, color: Colors.white)),
                );
              if (!_isDialogShowing && !_isScannerDeactivated) {
                if(error.errorCode == MobileScannerErrorCode.permissionDenied){
                  errorMessage = errorCameraPermissionDenied;
                  context.read<MobileScannerCubit>().checkCameraPermission();
                } else {
                  errorMessage = error.toString();
                }
              }
              return defaultError;
            },
 ```
  
  
  I extensively searched across your documentation and examples but couldnt find any examples to hint in this direction.
  
  If you could let me know, any ideas or or direction. 
  
  One of the major issues, i am facing is this even after configuring Camera Permission from settings, the Controller Error Widget goes on an inifinite loop of diaplying the error even when i have verified via `permission_handler` package that the permission status is `granted`

### PR DESCRIPTION
**Pull request by juliansteenbakker**
Fixes hot reload function by adding force parameter to `stop()`, and calling this on every start when `kDebugMode` is true. 
Merge after #1392 

Fixes #773 
Fixes #1037 
possibly fixes #1247

### CODE REVIEW

File: ios/Classes/MobileScanner.swift [hunk 1]
```diff
@@ -343,7 +345,9 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
     }
 
     private func releaseTexture() {
-        registry?.unregisterTexture(textureId)
+        if (textureId != nil) {
+            registry?.unregisterTexture(textureId)
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:349]: Do we need something similar on MacOS for this check?

File: lib/src/mobile_scanner.dart [hunk 2]
```diff
@@ -257,19 +259,21 @@ class _MobileScannerState extends State<MobileScanner>
   StreamSubscription? _subscription;
 
   Future<void> initMobileScanner() async {
-    // TODO: This will be fixed in another PR
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:260]: Can we add a TODO that links to https://github.com/flutter/flutter/issues/10437 when that API is eventually available?

File: lib/src/mobile_scanner.dart [hunk 3]
```diff
@@ -257,19 +259,21 @@ class _MobileScannerState extends State<MobileScanner>
...
     // every start is a hot-restart.
-    // if (kDebugMode) {
-    //   try {
-    //     await controller.stop();
-    //   } catch (e) {
-    //     // Don't do anything if the controller is already stopped.
-    //     debugPrint('$e');
-    //   }
-    // }
+    if (kDebugMode) {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:266]: I guess this is a decent workaround, until we have an actual API to detect this.

File: lib/src/mobile_scanner.dart [hunk 4]
```diff
@@ -257,19 +259,21 @@ class _MobileScannerState extends State<MobileScanner>
...
+      final platformInterface = MobileScannerPlatform.instance;
+      if (platformInterface is MethodChannelMobileScanner) {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:268]: Can we clean this up with an if-case? Just a suggestion though.

```suggestion
      if (MobileScannerPlatform.instance case final MethodChannelMobileScanner implementation) {
```

**Review by navaronbracke — APPROVED** [review]
LGTM, although I'd like to see the TODO link added for future reference.
