### PR TITLE
fix: rotation while locked for apple

### LINKED ISSUE #1588: Camera preview wrongfully rotates even when rotation is locked
## The problem
The Widget where I use the mobile scanner is locked to portrait orientation using [`SystemChrome.setPreferredOrientation`](https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html). But when the device rotates more than 45 degrees, the camera is rotated anyways. I expect `mobile_scanner` to respect the device orientations dictated by the native app (as defined in `AndroidManifest.xml` and `Info.plist`), and moreover the orientations as configured within Flutter using the `SystemChrome` API.

### Android
On Android, it doesn't matter if the system screen rotation is set to locked or unlocked: the camera view always rotates with the device (making it misalign with the real world when rotated, if the rest of the UI is locked). This seems to occur since a recent update, my previous app version used Flutter 3.35.3 and mobile_scanner 7.0.1, and the current version (where the bug occurs) is shown below. I also updated some transitive dependencies, so something may also have changed there

### iOS
On iOS, locking the screen rotation from the system tray _does_ prevent the bug from occurring. What's more, the issue was already occuring with the last version (the aforementioned Flutter 3.35.3 and mobile_scanner 7.0.1). It may be a separate issue from Android altogether, though the behavior is exactly the same on both systems.

## Flutter version
Flutter 3.35.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc9010625 (4 weeks ago) • 2025-10-21 14:16:03 -0400
Engine • hash 6b24e1b529bc46df7ff397667502719a2a8b6b72 (revision 035316565a) (28 days ago) • 2025-10-21 14:28:01.000Z
Tools • Dart 3.9.2 • DevTools 2.48.0

## Steps to reproduce
(verified on Android)
1. Clone this repository
2. Start the example app (on a real device)
3. Make sure system rotation is unlocked on the device
4. Open the _Simple Mobile Scanner_
5. Rotate the device and observe the camera preview adapts correctly, changing the rotation and aspect ratio
6. Lock the system rotation
7. If you now rotate > 45 degrees, the camera preview rotates but Flutter does not, misaligning the camera

## Possible resolution
Using the `MediaQuery` API on Android, we can detect whether Flutter is currently in a portrait or landscape orientation. It should be possible to use this information to prevent wrongful rotation (e.g. if the device is in landscape, but Flutter is still in portrait, the camera preview should _not_ be rotated). `MediaQuery` doesn't distinguish between the different portrait/landscape orientations though, so this could cause some struggles when flipping the device upside down.

## Videos

https://github.com/user-attachments/assets/315e2045-cd13-45e7-b5ee-ab838f8848bf

https://github.com/user-attachments/assets/c9f5d61c-44b7-4ffa-93cc-8e05dac5d247

### PR DESCRIPTION
**Pull request by juliansteenbakker**
Fixes #1588, camera rotating when rotation is enabled, but restricted via:

```dart
    SystemChrome.setPreferredOrientations(<DeviceOrientation>[
      DeviceOrientation.portraitUp,
    ]);
```

### CODE REVIEW

File: darwin/mobile_scanner/Sources/mobile_scanner/DeviceOrientationStreamHandler.swift [hunk 1]
```diff
@@ -44,25 +39,55 @@ class DeviceOrientationStreamHandler: NSObject, FlutterStreamHandler {
...
+            sink(orientationString)
+        } else {
+            // Fallback for iOS < 13: use device orientation
+            let orientation = UIDevice.current.orientation
+
+            if orientation == .faceUp || orientation == .faceDown {
+                return
+            }
+
+            let orientationString = orientation.toOrientationString
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/DeviceOrientationStreamHandler.swift:97]: Should we set lastSentOrientation here?

Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/DeviceOrientationStreamHandler.swift:97]: There is no check to not send an event if the orientation changed, for this code path?

**Review by navaronbracke — APPROVED** [review]
LGTM, with minor nits.

**Comment by navaronbracke** [comment]
@juliansteenbakker I probably forgot to ask, but is `setPreferredOrientations()` working correctly on Android with the latest patch? (I didn't verify that yet)

**Comment by juliansteenbakker** [comment]
Not yet i think, this patch is only for apple.

**Review by frankvollebregt — APPROVED** [review]
Thank you for looking into this issue :) I've just tested the version from this PR, and it looks like on iOS, this works as expected now for my use case (restricted device orientation using `SystemChrome` correctly prevents the preview from rotating, landscape allowed elsewhere in the app)

Tested on:
- iPhone XR (iOS 18.7.3)
- Flutter 3.38.8 / Dart 3.10.7

**Comment by navaronbracke** [comment]
@juliansteenbakker I have 2 minor questions on this PR (see above) but otherwise this is good to merge.

**Comment by juliansteenbakker** [comment]
Sorry for the delay. Thanks for the sharp eye @navaronbracke. I've added the check for that codepath aswell.

**Review by navaronbracke — APPROVED** [review]
New changes LGTM!
