### PR TITLE
fix: rotation while locked for android

### LINKED ISSUE #1588: Camera preview wrongfully rotates even when rotation is locked
## The problem
The Widget where I use the mobile scanner is locked to portrait orientation using [`SystemChrome.setPreferredOrientation`](https://api.flutter.dev/flutter/services/SystemChrome/setPreferredOrientations.html). But when the device rotates more than 45 degrees, the camera is rotated anyways. I expect `mobile_scanner` to respect the device orientations dictated by the native app (as defined in `AndroidManifest.xml` and `Info.plist`), and moreover the orientations as configured within Flutter using the `SystemChrome` API.

### Android
On Android, it doesn't matter if the system screen rotation is set to locked or unlocked: the camera view always rotates with the device (making it misalign with the real world when rotated, if the rest of the UI is locked). This seems to occur since a recent update, my previous app version used Flutter 3.35.3 and mobile_scanner 7.0.1, and the current version (where the bug occurs) is shown below. I also updated some transitive dependencies, so something may also have changed there

### iOS
On iOS, locking the screen rotation from the system tray _does_ prevent the bug from occurring. What's more, the issue was already occuring with the last version (the aforementioned Flutter 3.35.3 and mobile_scanner 7.0.1). It may be a separate issue from Android altogether, though the behavior is exactly the same on both systems.

## Flutter version
Flutter 3.35.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc9010625 (4 weeks ago) • 2025-10-21 14:16:03 -0400
Engine • hash 6b24e1b529bc46df7ff397667502719a2a8b6b72 (revision 035316565a) (28 days ago) • 2025-10-21 14:28:01.000Z
Tools • Dart 3.9.2 • DevTools 2.48.0

## Steps to reproduce
(verified on Android)
1. Clone this repository
2. Start the example app (on a real device)
3. Make sure system rotation is unlocked on the device
4. Open the _Simple Mobile Scanner_
5. Rotate the device and observe the camera preview adapts correctly, changing the rotation and aspect ratio
6. Lock the system rotation
7. If you now rotate > 45 degrees, the camera preview rotates but Flutter does not, misaligning the camera

## Possible resolution
Using the `MediaQuery` API on Android, we can detect whether Flutter is currently in a portrait or landscape orientation. It should be possible to use this information to prevent wrongful rotation (e.g. if the device is in landscape, but Flutter is still in portrait, the camera preview should _not_ be rotated). `MediaQuery` doesn't distinguish between the different portrait/landscape orientations though, so this could cause some struggles when flipping the device upside down.

## Videos

https://github.com/user-attachments/assets/315e2045-cd13-45e7-b5ee-ab838f8848bf

https://github.com/user-attachments/assets/c9f5d61c-44b7-4ffa-93cc-8e05dac5d247

### PR DESCRIPTION
**Pull request by juliansteenbakker**
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1588 for android, camera rotating when rotation is enabled, but restricted via:

    SystemChrome.setPreferredOrientations(<DeviceOrientation>[
      DeviceOrientation.portraitUp,
    ]);
    
    
 I did discover a bug with the overlay, which does not turn when the display rotates and rotation is enabled, but this is also presented in the develop branch, so should be handled by a different PR.

### CODE REVIEW

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt [hunk 1]
```diff
@@ -2,42 +2,40 @@ package dev.steenbakker.mobile_scanner
...
 import io.flutter.plugin.common.EventChannel
 
 /**
- * This class will listen to device orientation changes.
+ * This class listens to display orientation changes.
  *
- * When a new orientation is received, the registered listener will be invoked.
+ * The orientation is determined from the display rotation rather than raw sensor data.
+ * This ensures that the reported orientation respects both the system rotation lock
+ * andf Flutter [SystemChrome.setPreferredOrientations].
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt]: "and"

Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt]: `SystemChrome.setPreferredOrientations` is a Dart symbol, not a Kotlin Symbol, so this should be backticks?

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt [hunk 2]
```diff
@@ -2,42 +2,40 @@ package dev.steenbakker.mobile_scanner
...
  */
 class DeviceOrientationListener(
     private val activity: Activity,
-) : OrientationEventListener(activity, SensorManager.SENSOR_DELAY_NORMAL), EventChannel.StreamHandler {
```
Comment (navaronbracke) [inline android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt:26]: Would this fix https://github.com/juliansteenbakker/mobile_scanner/issues/1572 ?

**Review by navaronbracke — APPROVED** [review]
LGTM, with a minor question

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt (hunk 2 above)
Comment (juliansteenbakker) [reply android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt:26]: I guess so, no more need for `SensorManager`, that would be awesome! I've asked if someone can verify this.

File: android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt (hunk 1 above)
Comment (juliansteenbakker) [reply android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt]: You're right, lets change that

Comment (juliansteenbakker) [reply android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt]: Sharp as always 😄

**Comment by navaronbracke** [comment]
@juliansteenbakker What if we merge this, follow up with that overlay issue in a new PR and release this as a new version? Then more people will probably verify the sensor list bug. If we don't get any new reports by then, then we can probably close that issue.

**Comment by juliansteenbakker** [comment]
Sounds like a good plan, but ill continue on the overlay issue tomorrow.
