### PR TITLE
fix: remove unused child argument

### LINKED ISSUE #1256: `placeholderBuilder` and `errorBuilder` callbacks for `MobileScanner` have an extra argument which serves no purpose.
This is what the `build` method of the `MobileScanner` widget looks like:

```dart
@override
Widget build(BuildContext context) {
  return ValueListenableBuilder<MobileScannerState>(
    valueListenable: controller,
    builder: (BuildContext context, MobileScannerState value, Widget? child) {
      if (!value.isInitialized) {
        const Widget defaultPlaceholder = ColoredBox(color: Colors.black);

        return widget.placeholderBuilder?.call(context, child) ??
            defaultPlaceholder;
      }

      final MobileScannerException? error = value.error;

      if (error != null) {
        const Widget defaultError = ColoredBox(
          color: Colors.black,
          child: Center(child: Icon(Icons.error, color: Colors.white)),
        );

        return widget.errorBuilder?.call(context, error, child) ??
            defaultError;
      }

      return LayoutBuilder(
        builder: (context, constraints) {
          _maybeUpdateScanWindow(value, constraints);

          final Widget? overlay =
              widget.overlayBuilder?.call(context, constraints);
          final Size cameraPreviewSize = value.size;

          final Widget scannerWidget = ClipRect(
            child: SizedBox.fromSize(
              size: constraints.biggest,
              child: FittedBox(
                fit: widget.fit,
                child: SizedBox(
                  width: cameraPreviewSize.width,
                  height: cameraPreviewSize.height,
                  child: MobileScannerPlatform.instance.buildCameraView(),
                ),
              ),
            ),
          );

          if (overlay == null) {
            return scannerWidget;
          }

          return Stack(
            alignment: Alignment.center,
            children: <Widget>[
              scannerWidget,
              overlay,
            ],
          );
        },
      );
    },
  );
}
```

Since `child` is not passed to the `ValueListenableBuilder`, it will always be `null`. There is no point in making `placeholderBuilder` and `errorBuilder` callbacks take an extra argument.

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1256

### CODE REVIEW

File: lib/src/mobile_scanner.dart [hunk 1]
```diff
@@ -8,13 +8,6 @@ import 'package:mobile_scanner/src/objects/barcode_capture.dart';
 import 'package:mobile_scanner/src/objects/mobile_scanner_state.dart';
 import 'package:mobile_scanner/src/scan_window_calculation.dart';
 
-/// The function signature for the error builder.
-typedef MobileScannerErrorBuilder = Widget Function(
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:12]: Now that the function signature is short enough to fit on one line, I opted to remove the typedef

File: lib/src/mobile_scanner.dart [hunk 2]
```diff
@@ -73,7 +66,7 @@ class MobileScanner extends StatefulWidget {
   /// If this is null, a black [ColoredBox] is used as placeholder.
   ///
   /// The placeholder is displayed when the camera preview is being initialized.
-  final Widget Function(BuildContext, Widget?)? placeholderBuilder;
+  final WidgetBuilder? placeholderBuilder;
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:69]: Reusing an exiting typedef from the framework here

File: lib/src/mobile_scanner.dart [hunk 3]
```diff
@@ -203,12 +196,11 @@ class _MobileScannerState extends State<MobileScanner>
   Widget build(BuildContext context) {
     return ValueListenableBuilder<MobileScannerState>(
       valueListenable: controller,
-      builder: (BuildContext context, MobileScannerState value, Widget? child) {
+      builder: (BuildContext context, MobileScannerState value, _) {
```
Comment (navaronbracke) [inline lib/src/mobile_scanner.dart:199]: Users can create a child widget above the `MobileScanner` widget in their build method, which makes passing in a child widget redundant here. And as reported, the `child` parameter was unused, so it didn't add any value to the function signatures

File: example/lib/barcode_scanner_controller.dart [hunk 4]
```diff
@@ -65,7 +65,7 @@ class _BarcodeScannerWithControllerState
             child: Container(
               alignment: Alignment.bottomCenter,
               height: 100,
-              color: Colors.black.withOpacity(0.4),
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_controller.dart:68]: withOpacity is deprecated, so I replaced it everywhere

File: example/lib/scanner_error_widget.dart [hunk 5]
```diff
@@ -19,7 +19,6 @@ class ScannerErrorWidget extends StatelessWidget {
         errorMessage = 'Scanning is unsupported on this device';
       default:
         errorMessage = 'Generic Error';
-        break;
```
Comment (navaronbracke) [inline example/lib/scanner_error_widget.dart:22]: The linter now reports an obsolete break statement here
