### PR TITLE
fix: Adjust autoStart values for samples

### LINKED ISSUE #1058: Examples not functional anymore
Except for `barcode_scanner_simple` and `barcode_scanner_pageview` all examples give me the error:

'Generic Error: The scanner already started. Call stop() before calling start() again.'

### PR DESCRIPTION
**Pull request by navaronbracke**
When reintroducing the `autoStart` parameter, the samples were not accounted for. This PR adjusts the samples to automatically start, except for the lifecycle sample, which still manually starts. 

Fixes #1058

### CODE REVIEW

File: example/lib/barcode_scanner_controller.dart [hunk 1]
```diff
@@ -16,12 +16,9 @@ class BarcodeScannerWithController extends StatefulWidget {
 class _BarcodeScannerWithControllerState
     extends State<BarcodeScannerWithController> with WidgetsBindingObserver {
   final MobileScannerController controller = MobileScannerController(
-    torchEnabled: true, useNewCameraSelector: true,
-    // formats: [BarcodeFormat.qrCode]
-    // facing: CameraFacing.front,
-    // detectionSpeed: DetectionSpeed.normal
-    // detectionTimeoutMs: 1000,
-    // returnImage: false,
+    autoStart: false,
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_controller.dart:19]: Formatting + removing commented out code. Users can look at the API docs instead.

File: example/lib/barcode_scanner_pageview.dart [hunk 2]
```diff
@@ -13,17 +13,10 @@ class BarcodeScannerPageView extends StatefulWidget {
 }
 
 class _BarcodeScannerPageViewState extends State<BarcodeScannerPageView> {
-  final MobileScannerController controller =
-      MobileScannerController(autoStart: false);
+  final MobileScannerController controller = MobileScannerController();
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_pageview.dart:16]: I opted to use automatic starts here.

File: example/lib/barcode_scanner_returning_image.dart [hunk 3]
```diff
@@ -18,19 +18,9 @@ class _BarcodeScannerReturningImageState
     extends State<BarcodeScannerReturningImage> {
   final MobileScannerController controller = MobileScannerController(
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_returning_image.dart:19]: Is redundant with automatic start.

File: example/lib/barcode_scanner_window.dart [hunk 4]
```diff
@@ -17,13 +17,6 @@ class _BarcodeScannerWithScanWindowState
     extends State<BarcodeScannerWithScanWindow> {
   final MobileScannerController controller = MobileScannerController();
 
-  @override
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_window.dart:20]: Is redundant with automatic start.

File: example/lib/barcode_scanner_zoom.dart [hunk 5]
```diff
@@ -22,12 +22,6 @@ class _BarcodeScannerWithZoomState extends State<BarcodeScannerWithZoom> {
 
   double _zoomFactor = 0.0;
 
-  @override
-  void initState() {
```
Comment (navaronbracke) [inline example/lib/barcode_scanner_zoom.dart:26]: Is redundant with automatic start.

File: example/lib/mobile_scanner_overlay.dart [hunk 6]
```diff
@@ -15,12 +15,6 @@ class _BarcodeScannerWithOverlayState extends State<BarcodeScannerWithOverlay> {
     formats: const [BarcodeFormat.qrCode],
   );
 
-  @override
-  void initState() {
```
Comment (navaronbracke) [inline example/lib/mobile_scanner_overlay.dart:19]: Is redundant with automatic start.
