### PR TITLE
fix: Port scan timeout to iOS

### LINKED ISSUE #787: Bug at detectionTimeoutMS on iOS
I'm already at MobileScannerController Detectionspeed.normal and DetectionTimeoutMS 5000 but in iOS not working and in Android working normal

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR is a port of https://github.com/juliansteenbakker/mobile_scanner/pull/675 but for iOS.

That PR erroneously indicated iOS, but implemented it for MacOS instead.

Fixes #787

### CODE REVIEW

File: ios/Classes/MobileScanner.swift [hunk 1]
```diff
@@ -54,6 +54,12 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
     private let backgroundQueue = DispatchQueue(label: "camera-handling")
 
     var standardZoomFactor: CGFloat = 1
+    
+    private var nextScanTime = 0.0
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:58]: I made `timeoutSeconds` public, because on iOS the implementation is split over 2 files.

File: ios/Classes/MobileScanner.swift [hunk 2]
```diff
@@ -89,8 +95,15 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
         }
         latestBuffer = imageBuffer
         registry?.textureFrameAvailable(textureId)
-        if ((detectionSpeed == DetectionSpeed.normal || detectionSpeed == DetectionSpeed.noDuplicates) && i > 10 || detectionSpeed == DetectionSpeed.unrestricted) {
-            i = 0
+        
+        let currentTime = Date().timeIntervalSince1970
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:99]: `Date.now` is only available on iOS 15. Otherwise this is an exact copy of the other PR change.

File: ios/Classes/MobileScanner.swift [hunk 3]
```diff
@@ -301,7 +314,7 @@ public class MobileScanner: NSObject, AVCaptureVideoDataOutputSampleBufferDelega
         
         do {
             try device.lockForConfiguration()
-            var maxZoomFactor = device.activeFormat.videoMaxZoomFactor
+            let maxZoomFactor = device.activeFormat.videoMaxZoomFactor
```
Comment (navaronbracke) [inline ios/Classes/MobileScanner.swift:317]: Warning in XCode about a var that could be let.

File: ios/Classes/SwiftMobileScannerPlugin.swift [hunk 4]
```diff
@@ -168,7 +171,7 @@ public class SwiftMobileScannerPlugin: NSObject, FlutterPlugin {
     
     /// Toggles the zoomScale
     private func setScale(_ call: FlutterMethodCall, _ result: @escaping FlutterResult) {
-        var scale = call.arguments as? CGFloat
+        let scale = call.arguments as? CGFloat
```
Comment (navaronbracke) [inline ios/Classes/SwiftMobileScannerPlugin.swift:174]: Warning in XCode about a var that could be let.

File: ios/Classes/SwiftMobileScannerPlugin.swift [hunk 5]
```diff
@@ -103,7 +104,9 @@ public class SwiftMobileScannerPlugin: NSObject, FlutterPlugin {
         let formats: Array<Int> = (call.arguments as! Dictionary<String, Any?>)["formats"] as? Array ?? []
         let returnImage: Bool = (call.arguments as! Dictionary<String, Any?>)["returnImage"] as? Bool ?? false
         let speed: Int = (call.arguments as! Dictionary<String, Any?>)["speed"] as? Int ?? 0
-
+        let timeoutMs: Int = (call.arguments as! Dictionary<String, Any?>)["timeout"] as? Int ?? 0
```
Comment (navaronbracke) [inline ios/Classes/SwiftMobileScannerPlugin.swift:107]: This was ported from the other PR, keeping in mind your earlier comment about the division.
