### PR TITLE
fix: handle errors from cvcreatepixelbuffer

### LINKED ISSUE #1545: [iOS] EXC_BREAKPOINT crash in captureOutput when VTCreateCGImageFromCVPixelBuffer fails
markdown## Description
The iOS app crashes with an `EXC_BREAKPOINT` exception in the `captureOutput(_:didOutput:from:)` method when `VTCreateCGImageFromCVPixelBuffer` fails to create a CGImage from the pixel buffer. This occurs when the camera is interrupted (phone calls, app switching, backgrounding) or when the pixel buffer becomes invalid.

## Environment
- **mobile_scanner version:** 7.1.2
- **Platform:** iOS
- **iOS version:** 17.x (likely affects other versions)
- **Device:** Real devices (not simulator specific)
- **Flutter version:** [Your Flutter version]
- **Dart version:** [Your Dart version]

## Stack Trace
Crashed: com.apple.root.user-initiated-qos
EXC_BREAKPOINT 0x000000019537a280
0  CoreFoundation                 0x5280 <redacted> + 64
1  CoreVideo                      0x6448 <redacted> + 28
2  CoreVideo                      0x6a20 CVPixelBufferGetWidth + 16
3  VideoToolbox                   0x41433c VTCreateCGImageFromCVPixelBuffer + 244
4  mobile_scanner                 0x63b8 $s14mobile_scanner19MobileScannerPluginC13captureOutput_03didG04fromySo09AVCaptureG0C_So17CMSampleBufferRefaSo0J10ConnectionCtFyyYbcfU_ + 272
5  mobile_scanner                 0x85d8 $sIeg_IeyB_TRTm + 28
6  libdispatch.dylib              0x1adc <redacted> + 32
...

## Steps to Reproduce
1. Open the scanner
2. Start scanning
3. Trigger a camera interruption by:
   - Receiving a phone call
   - Switching to another app quickly
   - Putting the device to sleep
   - Backgrounding the app mid-scan
4. App crashes with EXC_BREAKPOINT

## Expected Behavior
The scanner should handle camera interruptions gracefully without crashing. The app should either:
- Skip the invalid frame silently
- Show an error message
- Restart the camera session

## Actual Behavior
The app crashes immediately with `EXC_BREAKPOINT` when `VTCreateCGImageFromCVPixelBuffer` returns a nil `CGImage`.

## Root Cause
In `MobileScannerPlugin.swift`, the `captureOutput` method force-unwraps the `CGImage` without checking if `VTCreateCGImageFromCVPixelBuffer` succeeded:
```swift
var cgImage: CGImage?
VTCreateCGImageFromCVPixelBuffer(self.latestBuffer, options: nil, imageOut: &cgImage)
let imageRequestHandler = VNImageRequestHandler(cgImage: cgImage!)  // ⚠️ CRASHES HERE



Proposed Fix
Add proper error checking for the VTCreateCGImageFromCVPixelBuffer result:
swiftvar cgImage: CGImage?
let status = VTCreateCGImageFromCVPixelBuffer(buffer, options: nil, imageOut: &cgImage)

// Check if image creation succeeded
guard status == kCVReturnSuccess, let validImage = cgImage else {
    self.imagesCurrentlyBeingProcessed = false
    return
}

// Now safe to use validImage
let imageRequestHandler = VNImageRequestHandler(cgImage: validImage)


Additional Context

This is a regression or newly discovered bug in version 7.1.2
Similar force-unwrap issues were fixed in previous versions (see #720)
The crash occurs on the user-initiated-qos queue, indicating it's during normal barcode processing
The imagesCurrentlyBeingProcessed flag should also be reset when errors occur to prevent the scanner from getting stuck

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1545

### CODE REVIEW

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 1]
```diff
@@ -132,10 +132,11 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
     
     // FlutterTexture
     public func copyPixelBuffer() -> Unmanaged<CVPixelBuffer>? {
-        if latestBuffer == nil {
+        guard let buffer = latestBuffer else {
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:135]: Just in case, also use a guard let here

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 2]
```diff
@@ -265,7 +283,7 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
 
     func updateScanWindow(_ call: FlutterMethodCall, _ result: @escaping FlutterResult) {
         let argReader = MapArgumentReader(call.arguments as? [String: Any])
-        let scanWindowData: Array? = argReader.floatArray(key: "rect")
+        let scanWindowData: [CGFloat]? = argReader.floatArray(key: "rect")
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:286]: This was indeed `[CGFloat]?` in the arg reader

File: darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift [hunk 3]
```diff
@@ -190,29 +204,31 @@ public class MobileScannerPlugin: NSObject, FlutterPlugin, FlutterStreamHandler,
...
+                        var bytes: FlutterStandardTypedData? = nil
+                        
+                        if MobileScannerPlugin.returnImage,
+                           let imageBytes = currentImage.jpegData(compressionQuality: 0.8) {
+                            bytes = FlutterStandardTypedData(bytes: imageBytes)
+                        }
 
                         DispatchQueue.main.async {
-                            // If the image is nil, use zero as the size.
-                            guard let image = cgImage else {
```
Comment (navaronbracke) [inline darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift:196]: This check is no longer needed

**Comment by navaronbracke** [comment]
@juliansteenbakker I would like to release this as the definitive `7.1.3` version, since it hotfixes a rather annoying bug on iOS / MacOS.

**Review by juliansteenbakker — APPROVED** [review]
Looks good to me. Tested on iPhone, and did not see any difference with current version.

**Comment by venn710** [comment]
I am still getting this issue in latest 7.1.4 version also
Here is the stacktrace

Crashed: com.apple.root.user-initiated-qos
0  libobjc.A.dylib                0x1cf4 objc_msgSend + 20
1  mobile_scanner                 0xdf24 closure 1 in MobileScannerPlugin.captureOutput(_:didOutput:from:) + 174 (MobileScannerPlugin.swift:174)
2  mobile_scanner                 0x101c8 thunk for @escaping @callee_guaranteed () -> () + 28
3  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
5  libdispatch.dylib              0x13cbc _dispatch_root_queue_drain + 636
6  libdispatch.dylib              0x1439c _dispatch_worker_thread2 + 172
7  libsystem_pthread.dylib        0x1dc4 _pthread_wqthread + 224
8  libsystem_pthread.dylib        0x192c start_wqthread + 8
